### ISSUE TITLE
Rscript warnings!

### ISSUE THREAD

**Issue by nbawe** [xavierdidelot/ClonalFrameML#102]
Hello  I was using CFML Rscript on MacOS with Rscript v3.6.2 and got following warnings - can I ignore those:

```
Rscript cfml_results.R cfml_results
Read 1095025 items
Read 1298 items
Warning message:
NAs introduced by coercion 
Warning message:
In ifelse(is.na(as.numeric(tree$tip.label)), tree$tip.label, paste("C0000",  :
  NAs introduced by coercion
Warning message:
In ifelse(is.na(as.numeric(rownames(wh.mut))), rownames(wh.mut),  :
  NAs introduced by coercion
null device 
          1 
[[1]]
NULL

... #went up until the end (I deleted 2 - 323 lines just to save space) 

[[324]]
NULL

null device 
          1 
```

**Comment by xavierdidelot** [comment]
Yes you can ignore these warnings as long as the pdf is generated.

**Comment by nbawe** [comment]
Thank you! I have one more question regarding Rscript output.

```
Read 1095025 items
Read 1298 items
```

First row is sequence length, but could you tell me what is the second row `1298`?

**Comment by xavierdidelot** [comment]
That's the number of lines in the file with suffix .ML_sequence.fasta

**Comment by nbawe** [comment]
Thank you!

**Comment by tbazilegith** [comment]
Hi  Xavier,
I have the same warning and pdf file is generated. However, some of my genomes do not show on tree. Any ideas?
NULL

[[22]]
NULL

[[23]]
NULL

[[24]]
NULL
...
[[84]]
NULL

[[85]]
NULL
Thanks,
TJ

**Comment by xavierdidelot** [comment]
You can ignore the warnings. Sometimes labels are not shown if they are too long, you will have to edit the script to solve this or add the labels separately.
