### ISSUE TITLE
Parameters -em TRUE and -emsim 100

### ISSUE THREAD

**Issue by nbawe** [xavierdidelot/ClonalFrameML#103]
Is it correct to use `-em TRUE` and `-emsim 100` together as follows:

`clonalframeml RAxML_bestTree.automre core_genomes.fas cfml_emsim -em true -emsim 100 -output_filtered true -show_progress true`

**Comment by xavierdidelot** [comment]
Yes this command is fine or you could remove the -em true since this is the default behaviour anyway.
