### ISSUE TITLE
importation_status.txt output clarification

### ISSUE THREAD

**Issue by madeleinevlt** [xavierdidelot/ClonalFrameML#104]
Hello,

I am trying to find hotspots of recombination as you made in your article.

If I understand well, for your Staphylococcus aureus and Clostridium difficile ST6 data you looked at the importation_status.txt file, and checked the position to obtain the corresponding sequence. 

And node positions mean that every samples on this node have this recombinaison event.

Is that true ?

Thanks

**Comment by xavierdidelot** [comment]
Yes you can use this file to determine if and where there are any recombination hotspot.
The first column indicates on which branch the recombination events happened, and all genomes that are descended from that branch will contain the recombination event.
The second and third columns indicate the start and end points of the recombination events along the genome alignment.
