### ISSUE TITLE
Drake's rule and molecular evolution

### ISSUE THREAD

**Issue by megaptera-helvetiae** [xavierdidelot/ClonalFrameML#107]
Is there a specific output from ClonalFrameML that can be used to calculate Drake's value? We would like to know how long it would take the clonal frame to change into a new species (1 mutation per genome every 300 generations).

**Comment by xavierdidelot** [comment]
What you get out of ClonalFrameML is the number of mutations separating the genomes, but for Drake's rule you would need to estimate the number of mutations per unit of time. You can do this for example using my other software BactDating https://github.com/xavierdidelot/BactDating which can use as its input the recombination-corrected outputs of ClonalFrameML.
