### ISSUE TITLE
Calculate nucleotide diversity within and outside the clonal frame

### ISSUE THREAD

**Issue by megaptera-helvetiae** [xavierdidelot/ClonalFrameML#108]
Dear Xavier, 
as you can see in issue #107, we are getting a bit more adventurous. Hence also my next question:
Is there a way in ClonalFrameML to calculate nucleotide diversity within and outside the clonal frame (so including and excluding the parts that are recombining)? This would be similar to the output of Gubbins: https://sanger-pathogens.github.io/gubbins/

Thank you.

Laetitia and my allies.

**Comment by xavierdidelot** [comment]
I would say that the best way to do this is to compare the branch lengths in the tree before correcting for recombination (ie the tree input file of ClonalFrameML) and after correcting for recombination (ie the tree output file of ClonalFrameML). If by "diversity" you mean pairwise diversity, you could calculate and compare the patristic distance between pairs of leaves in both trees.
