### ISSUE TITLE
different outputs with different parameters, how to choose the rihgt one?

### ISSUE THREAD

**Issue by cheerupgirls** [xavierdidelot/ClonalFrameML#109]
Hi Xavier,
what does it mean that the output is being too conservative in issue #30? Any method to identify it?
Is it normal that the outputs vary with differernt parameter (such as -embranch_dispersion or model) or subsets of my data? 
I'm not sure weather this result is due to my sample size is small (37, but some of them are very similar ) or something else. Any advice is welcome, thank you.

Best wishes,
Ajiao

**Comment by xavierdidelot** [comment]
Hi Ajiao,

In issue #30 by "too conservative" I meant that ClonalFrameML detects a lot less recombination than you would expect. Yes you would expect to get different outputs when you use different parameter values, especially on a small dataset. For a small dataset it is probably best to stick with the default (ie not per-branch) model.

Best wishes,
Xavier

**Comment by cheerupgirls** [comment]
Hi&nbsp;Xavier,


I got it. Thank you so much for your reply.


Best wishes,
 Ajiao



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xavierdidelot/ClonalFrameML"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 下午4:21
收件人:&nbsp;"xavierdidelot/ClonalFrameML"<ClonalFrameML@noreply.github.com&gt;;
抄送:&nbsp;"王姣"<1434371350@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [xavierdidelot/ClonalFrameML] different outputs with different parameters, how to choose the rihgt one? (#109)





 
Hi Ajiao,
 
In issue #30 by "too conservative" I meant that ClonalFrameML detects a lot less recombination than you would expect. Yes you would expect to get different outputs when you use different parameter values, especially on a small dataset. For a small dataset it is probably best to stick with the default (ie not per-branch) model.
 
Best wishes,
 Xavier
