### ISSUE TITLE
Interpreting a long blue line in output figure

### ISSUE THREAD

**Issue by megaptera-helvetiae** [xavierdidelot/ClonalFrameML#111]
Hi Xavier,

I am wondering what it means if one individual in my analysis (or sometimes an ancestral node) is all colored in blue? As if the whole genome recombined. Is this an indication that this individual might be a different species? The ANI values are ~96%. 

Please also see the attached figures. 

Thank you!

Laetitia

[sisters.pdf](https://github.com/xavierdidelot/ClonalFrameML/files/5212668/sisters.pdf)

[Rugie_middle.pdf](https://github.com/xavierdidelot/ClonalFrameML/files/5212669/Rugie_middle.pdf)

**Comment by xavierdidelot** [comment]
Hi Laetitia,

This is an indication that (almost) the whole genome has recombined on that branch, and that the clonal signal is (almost) erased throughout the genome. This does not mean that it is a different species though, this can happen within a species if it is a highly recombinant species. In the figures you attached, you can see some relatively short branches on which ~50% of the genome is recombined. So it makes sense that on the longer branches we would expect >95% of the genome to have recombined.

Best wishes,
Xavier
