### ISSUE TITLE
R script location

### ISSUE THREAD

**Issue by martinastoycheva** [xavierdidelot/ClonalFrameML#113]
Hello, 

I installed ClonalFrameML using Conda and was wondering where the Rscripts for graphics are located. In the wiki it says they should be in the snv directory but I cannot find a directory with that name on the github or in the conda container. Could you please point me to their location?

Cheers, 
Martina

**Comment by xavierdidelot** [comment]
Hi Martina,

I'm not sure if the conda installation includes the R script for producing the graphical output, but if not you can get it from:
https://raw.githubusercontent.com/xavierdidelot/ClonalFrameML/master/src/cfml_results.R

Best wishes,
Xavier
