### ISSUE TITLE
Can I get branch-specific values for R/Theta, 1/delta and nu from a standard CFML run?

### ISSUE THREAD

**Issue by jodsikorski** [xavierdidelot/ClonalFrameML#115]
Dear Xavier,

When running CFML in standard mode (default settings) the *em.txt output file provides me on the first 4 lines the recombination parameter for the entire data set.
However, from line 5 on, the *em.txt output file provides me per branch with additional 4 values which I do not yet have understood to what they refer to. What are these values? (I am not sure if they present the branch values.)

Please find below the first six lines of the *em.txt output file.
Would it be possible to calculate from this output (standard model, default settings) the branch-specific values of the recombination parameter, without necessarily running CFML in the branchspecific mode (-embranch true)? If yes, then again by multiplying the values with the mean (which I assume are in lines 2-4)?

Thanks for your help, best,
Johannes

Parameter	Posterior Mean	Posterior Variance	a_post	b_post
R/theta	0.129686	3.21547e-06	5230.45	40331.8
1/delta	0.013032	3.24761e-08	5229.45	401279
nu	0.108303	2.70561e-07	43352.6	400290
Psal182	4.01294e-05	2.71643e-11	59.2827	1.47729e+06
AY6492A	1.98804e-06	1.34551e-12	2.9374	1.47754e+06

**Comment by xavierdidelot** [comment]
Dear Johannes,

When running in the default setting, the values in the em.txt from line 5 concern the lengths of the branches in the tree. You cannot deduce from this the branch-specific values of recombination parameters. To get this, you need to run with the -embranch true option.

Best wishes,
Xavier

**Comment by jodsikorski** [comment]
Dear Xavier,
thanks a lot for the information.
best,
Johannes
