### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by spencer411** [xavierdidelot/ClonalFrameML#116]
I am trying to use this program, but I get a segmentation fault error. I am running it as follows and get the corresponding error:

(clonalframeml) -bash-4.2$ ClonalFrameML aureus_tree.tre core_alignment.xmfa clonal_out -xmfa_file true

ClonalFrameML v1.12
xmfa_file = true
Finished reading in control file.

/tmp/slurmd/job2421871/slurm_script: line 14: 42011 Segmentation fault      ClonalFrameML aureus_tree.tre core_alignment.xmfa clonal_out -xmfa_file true

Note that my .xmfa file is pretty large (125MB). I have tried running it on a smaller .fa file to test with no problem. Any help is appreciated.

**Comment by xavierdidelot** [comment]
I think your previous problem was because you were not using the argument "-xmfa_file true"
The segmentation fault is harder to diagnose. 125MB should be no problem at all. 
Could you try to run on just the first two loci of your xmfa file, so truncating this file after the second "=" symbol?

**Comment by spencer411** [comment]
I created a .fa file instead and it seems to be working fine now. It may have been a problem with some of the characters which I have since replaced with "N". Seems to be running well. Thanks so much for the speedy reply!
