### ISSUE TITLE
Using Mummer output as CFML input

### ISSUE THREAD

**Issue by edsonmachado** [xavierdidelot/ClonalFrameML#117]
Hi Xavier,

I've seen you suggesting try to use Mummer to align genomes against a reference as a possible input to CFML. I haven't use Mummer so far, but I would like to follow your suggestion. However, looking to Mummer documentation, it seems that output files don't fit directly to CFML as input (alignment or XMFA).

Do you have some information about pre-processing Mummer output files before going into CFML?

Best regards

**Comment by xavierdidelot** [comment]
Yes indeed mummer does not directly generate an alignment in fasta format and so you would need to write or find a script to do this.
