### ISSUE TITLE
Rscript output

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xavierdidelot/ClonalFrameML#12]
```
Hi

Just wondering if there is any documentation available, or if you could explain 
what the color scheme represents in the pdf that is generated with the 
cfml_results.R script.

As far as I can gather, light blue represents all invariant sites, white all 
variant sites and dark blue the regions deemed recombinant (please correct if 
this is wrong). However, I am not sure about the yellows, oranges and reds. 
(pdf attached)

Any help would be greatly appreciated.

Sarah



```

Original issue reported on code.google.com by `Sarah.L....@gmail.com` on 24 Apr 2015 at 5:19

Attachments:
- [example.pdf](https://storage.googleapis.com/google-code-attachments/clonalframeml/issue-12/comment-0/example.pdf)

**Comment by diaz13** [comment]
Hello
I used your tools clonalframeml that is very good to detect recombination.
But I had a question concerning the figure below.

Why I have a recombinations in legends and there's no genome ?
And Why I have the recombinaison almost all along the bottom line between JHQH01 and CVRH01 ? 
[projet3.output.cfml.pdf](https://github.com/xavierdidelot/ClonalFrameML/files/583492/projet3.output.cfml.pdf)

**Comment by xavierdidelot** [comment]
Thanks for using ClonalFrameML!
There are some recombination events even on the internal branches of
the tree, which is why you have some rows of the recombination matrix
without genome names, they correspond to internal branches aligned to
them on the tree. I don't know why you have so much recombination on
the branch ancestral to both JHQH01 and CVRH01, maybe these two
genomes have a lot of differences with the others.

Best wishes,
Xavier

**Comment by diaz13** [comment]
Thanks you 
Best wishes

**Comment by karchern** [comment]
Xavier, could you comment a bit more on what exactly you mean by 'substitution'? I.e., what does it tell us if there is phylogeny with a lot inferred substitutions (either homoplasic or non-homoplasic)?

Thank you for the awesome support, by the way!

**Comment by xavierdidelot** [comment]
A substitution is either a de novo mutation (if not in a dark blue horizontal bar) or an imported mutation (if within a dark blue horizontal bar).

**Comment by FilipeMatteoli** [comment]
Salut Mr. Xavier,
I am trying to identify the clonal groups based on SNPs phylogeny, i've extracted them, aligned and performed variable sites phylogeny in RaxML. Do i need to specify any parameter when using only SNP based phylogeny tree to run ClonalFrameML

**Comment by xavierdidelot** [comment]
It should be fine if your initial tree was based only on SNPs, but the alignment input into ClonalFrameML needs to include both SNPs and non-variable sites.
