### ISSUE TITLE
cfml_results.R error

### ISSUE THREAD

**Issue by maguileraf** [xavierdidelot/ClonalFrameML#120]
I get the attached error when using the script to generate the output figure. Do you know how to fix this?
<img width="988" alt="Screen Shot 2021-02-07 at 6 03 50 PM" src="https://user-images.githubusercontent.com/49694113/107162114-0d476080-696f-11eb-8759-5c0bf892b670.png">

**Comment by xavierdidelot** [comment]
Someone else had a similar problem before, cf issue #86, and it had happened because the files output by ClonalFrameML had been modified before calling the R script. Could you please confirm that you are trying to run the R script on exactly the same files that were output by ClonalFrameML?

**Comment by maguileraf** [comment]
Yes, I do not think I have modified these files.

**Comment by xavierdidelot** [comment]
This error happens on the line that is meant to display the recombination events. I'm wondering if maybe this is happening because ClonalFrameML did not find any recombination event at all. Could you please check how many lines you have in your output file with suffix .importation_status.txt ?

**Comment by maguileraf** [comment]
It has 7164 lines

**Comment by xavierdidelot** [comment]
Ok, so that's not the problem. 
If you would like to send me your files by email I will see if I can reproduce and understand the problem.

**Comment by maguileraf** [comment]
please! What email address should I send them to?

**Comment by xavierdidelot** [comment]
Cf http://xavierdidelot.github.io/contact.html

**Comment by xavierdidelot** [comment]
Solved - the ClonalFrameML output files had been edited.
