### ISSUE TITLE
Question: xmfa format?

### ISSUE THREAD

**Issue by nbawe** [xavierdidelot/ClonalFrameML#122]
I have two formats of xmfa files:

1) with #:
```
#Gene_name1
>Isolate1
ATG...TGC
>Isolate2
ATG...TGC
=
#Gene_name2
>Isolate1
ATG...TGC
>Isolate2
ATG...TGC
=
```
2) without #:
```
>Isolate1:1-10 + Gene_name1
ATG...TGC
>Isolate 2:1-10 + Gene_name1
ATG...TGC
=
>Isolate1:11-20 +Gene_name2
ATG...TGC
>Isolate2:11-20 + Gene_name2
ATG...TGC
=
```

My question are both suitable for CFML and what does ‘#’ represent - comment?

**Comment by nbawe** [comment]
Also in the first case the xmfa doesn’t end with `=` but in the second case it does. Does it matter in cfml?

**Comment by nbawe** [comment]
PS! I have edited my original question!

**Comment by xavierdidelot** [comment]
The lines starting with # are comments and should not have any effect.

**Comment by nbawe** [comment]
Thank you!

**Comment by nbawe** [comment]
@xavierdidelot one more question. I have tree file with names like: `>22275|OXC7093` but xmfa has names like: `>22275|OXC7093:1-1323 + CAMP0001`. I ran CFML using the mentioned files and it finished without any errors. The CFML output has names like in the tree file `22275|OXC7093`.

My question is how does CFML handles the differences in the names? Does it exclude everything after colon (including colon sign)?

Thank you for the answer

**Comment by nbawe** [comment]
I wanted to clarify where the difference comes from. I am using pubMLST database, where I got concatenated core fasta from which I build tree with RAxML. RAxML generated tree is used in combination with pubMLST database core xmfa using CFML. So the names differ as mentioned in previous comment.

**Comment by xavierdidelot** [comment]
Yes, ClonaFrameML ignores everything after the colon in the fasta headers.

**Comment by nbawe** [comment]
Thank you!
