### ISSUE TITLE
Recombination events total

### ISSUE THREAD

**Issue by martinastoycheva** [xavierdidelot/ClonalFrameML#123]
Hello,

This is probably a a dumb question but I cannot figure out the answer so I apologise in advance for that!
I ran ClonalFrameML for the first time and I am wondering how to get the total number of recombination events. There is an output file .importantion_status.txt and am I correct in thinking that if I count the number of lines of that file, it should give me the sum of the mutation and recombination events. How do I seperate out the number of recombination events only?

Cheers, 
Martina

**Comment by xavierdidelot** [comment]
Hi Martina,

This file .importantion_status.txt contains the list of recombination events only (not mutations) so if you could how many lines it contains you will get the total number of recombination events.

Best wishes,
Xavier
