### ISSUE TITLE
ERROR:  incompatible with a bifurcating unrooted tree

### ISSUE THREAD

**Issue by LeonardosMageiros** [xavierdidelot/ClonalFrameML#125]
Hi, 

I am running clonalframeML and I am having the following error message: 
ERROR: convert_NewickTree_to_marginal_tree(): Number of descendant nodes (4) incompatible with a bifurcating unrooted tree

Do you know what is going wrong and how I can fix this? The tree I am using has been produced using fasttree. 

Thank you in advance 
Leonardos

**Comment by xavierdidelot** [comment]
Hi Leonardos,

ClonalFrameML does not allow multichotomies in the input tree (except for the root which is allowed to have three descendants since the tree is seen as unrooted). You could resolve this for example using the "multi2di" command of the R package ape.

Best wishes,
Xavier
