### ISSUE TITLE
How to solve problems about "makefile", Thanks a lot!

### ISSUE THREAD

**Issue by nolan12333** [xavierdidelot/ClonalFrameML#128]
Dear,
When I install this the most up to date version of ClonalFrameML by downloading and compiling the C++ source code via GIT using the command:
(base) [xxnolan@fat src]$ make
g++ -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data1/xqzang/miniconda3/include -O3 -c -o main.o main.cpp
g++: 错误：unrecognized command line option ‘-fno-plt’
make: *** [makefile:15: main.o] Error 1

How to solve it？
Thanks a lot!

**Comment by xavierdidelot** [comment]
Could you please try to compile with the following command
`g++ main.cpp -o ClonalFrameML -O3`

**Comment by nolan12333** [comment]
> Could you please try to compile with the following command
> `g++ main.cpp -o ClonalFrameML -O3`

Thanks a lot, it was solved! 
Thanks 😄
