### ISSUE TITLE
R values for calculation of R*delta

### ISSUE THREAD

**Issue by cbreusing** [xavierdidelot/ClonalFrameML#132]
Dear Xavier,

I was wondering if it is possible to get separate values for R from the ClonalFrameML analyses (i.e., not the R/theta ratios but the actual values for R). We would like to include some estimates of R*delta in a manuscript we are currently preparing to confirm the robustness of the results, given that the ClonalFrameML paper mentions that this factor is the main indicator for the reliability of the inferences. It is currently not clear to me how I can get to these values with the parameters that are reported. I have looked through the plots and they look fine (no straight blue lines), but it would be great to have some actual values for the supplement.

I hope you can give me some advice on this.

Thank you,
Corinna

**Comment by xavierdidelot** [comment]
Dear Corinna,

Indeed ClonalFrameML does not estimate `R` separately. If you want to do this, you will need to multiply the value of `R/theta` with an estimate of `theta`. You could use the Watterson estimator which is given by: `theta=L*G/An` where `L` is the sum of the branch lengths in the recombination-corrected tree, `G` is the length of the alignment and `An` is the sum of the `1/i` for `i` ranging from `1` to `n-1` with `n` being your number of genomes.

Best wishes,
Xavier

**Comment by cbreusing** [comment]
Dear Xavier,

Thank you so much for your advice. This has helped me a lot.

Corinna
