### ISSUE TITLE
Recombination filtered output vs importation_status.txt

### ISSUE THREAD

**Issue by raufs** [xavierdidelot/ClonalFrameML#133]
Hi Xavier,

Thank you for developing and maintaining this extremely useful program. 

Should the recombination filtered output produced by "-output_filtered true" be equivalent to filtering the input FASTA alignment by all sites listed in the importation_status.txt output file?

Kind regards,
Rauf

**Comment by xavierdidelot** [comment]
Hi Rauf,

Yes that is correct.

Best wishes,
Xavier
