### ISSUE TITLE
why the r/m I calculated is so small using a subclone of subclone of klebsiella pneumoniae

### ISSUE THREAD

**Issue by xuechunxu** [xavierdidelot/ClonalFrameML#134]
Hi Torsten,
I used a set of genomes from KL subclone of ST subclone of klebsiella pneumonia to calculate their recombination. The r/m is very small. I guess it is because my genomes are very similar and the diversity is low, but I am not sure. Is this result accurate?
![image](https://user-images.githubusercontent.com/23622076/189257934-94115e38-3666-4702-9492-b13799af896f.png)

Thanks
ChunXu

**Comment by xavierdidelot** [comment]
Hi ChunXu,

I can confirm that your calculation is correct, ie r/m=(R/theta)*delta*nu
The values of delta and nu are reasonable, but the values of R/theta are very low, which is why you get such low r/m.

Best wishes,
Xavier
