### ISSUE TITLE
std::bad_alloc problem

### ISSUE THREAD

**Issue by DorothyTamYiLing** [xavierdidelot/ClonalFrameML#136]
Hi,

First of all, thanks for writing ClonalFrameML, it is a really useful piece of software.

I am trying to run ClonalFrameML with my alignment and tree of 3000+ samples. Each sample is 4,607,202bp long so it is quite a large dataset. I ran ClonalFrameML on Amazon web service and I was using the most powerful instance (96vCPU and 192 Memory GiB), and I received the following error message:

/home/ec2-user/ClonalFrameML/src/ClonalFrameML S-flex.snp-sites.fasta.treefile.mid2.tre \
mapping-S_flex_2a.masked_rename.aln S-flex_ClFrML_out -kappa 4.592

ClonalFrameML v1.12
kappa = 4.592
Finished reading in control file.

Read 3191 sequences of length 4607202 sites from mapping-S_flex_2a.masked_rename.aln
IMPUTATION AND RECONSTRUCTION OF ANCESTRAL STATES:
Analysing 96300 sites
Empirical nucleotide frequencies:   A 24.6%   C 25.6%   G 25.4%   T 24.5%
Maximum log-likelihood for imputation and ancestral state reconstruction = -3.34037e+06
Wrote imputed and reconstructed ancestral states to S-flex_ClFrML_out.ML_sequence.fasta
Wrote position cross-reference file to S-flex_ClFrML_out.position_cross_reference.txt

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

I am wondering if the running out of RAM situation is due to the AWS instance not being powerful enough, or is it due to ClonalFrameML? 

How many samples can ClonalFrameML handle, as a rule of thumb? I would not mind to wait for a week or so, but is there a way to speed up ClonalFrameML when it comes to large dataset?

Many thanks for your attention,
Dorothy

**Comment by xavierdidelot** [comment]
Dear Dorothy,

I have not come across this problem before, but then again I have not tried to run ClonalFrameML on such a larger number of genomes. I think even if you manage to get it run it will be quite hard to make sense of the results. Perhaps you could consider either thinning down the number of genomes by removing close relatives, or spliting up the dataset into multiple lineages that can be analysed separately.

Best wishes,
Xavier
