### ISSUE TITLE
Are there any detailed description of the output pdf from cfml_results.R?

### ISSUE THREAD

**Issue by 1996xjm** [xavierdidelot/ClonalFrameML#137]
<img width="246" alt="image" src="https://user-images.githubusercontent.com/42203541/208813134-1141df96-364b-4572-87d6-18de3fc92b93.png">
I want to know what different colors of vertical bars represent?

- "skyblue" 
- "white"
- "yellow"
- "orange"
- "red"

@tseemann 
@xavierdidelot

**Comment by xavierdidelot** [comment]
The dark blue horizontal bars represent recombination. 
If a site does not change on a given branch, it is shown in light blue. 
If a site changes on a given branch, it is shown in a color indicating its level of homoplasy: white is no homoplasy and the range from yellow to orange to red is increasing degrees of homoplasy.
