### ISSUE TITLE
Can I use SNP multiple sequence alignment matrix and a tree build based on it as inputs?

### ISSUE THREAD

**Issue by CJJ8848** [xavierdidelot/ClonalFrameML#142]
Hi,

I created a SNP matrix only including variant sites presenting in all 72 samples and generated a tree based on the phy file converted from the SNP matrix using IQTREE. Then I input the fasta file converted from the phy file and the tree from IQTREE to CFML. It worked but removed so many recombination events for majority of branches. Could you please tell me whether I used the wrong input? I will be very appreciated!

**Comment by xavierdidelot** [comment]
No you can't do that. For ClonalFrameML to work your input fasta file needs to contain the non-polymorphic sites. This is needed for the detection of recombination. If you know the position of your SNPs along a reference genome you should be able to generate the full alignment as needed.

**Comment by xavierdidelot** [comment]
I would suggest to use the standard model, and you can get an estimate of the relative effect of recombination vs mutation `r/m` for each branch using the formula `r/m=(t1-t2)/t2` where `t1` is the branch length before correcting for recombination and `t2` is the branch length after correcting for recombination.

**Comment by CJJ8848** [comment]
Hi,

Thank you very much for the detailed explanation! I would like to double check that the relative effect of recombination to mutation should equal to (ratio of recombination rate to mutation rate x recombination length x nu) as described in your paper. And here you mean I could calculate the ratio of recombination rate to mutation rate based on these two formulas? Like first calculate the r/m using t1 and t2 here and then calculate the branch-specific recombination rate using the formula given in the paper. Thank you very much!

Jim

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
