### ISSUE TITLE
 contructed a new whole genome alignment

### ISSUE THREAD

**Issue by liuxiong714** [xavierdidelot/ClonalFrameML#143]
Thanks very much for your excellent recombination analysis tool !

I have constructed a whole genome alignment ( A ) from snippy software.
then a phylogenetic tree ( T ) was build by iqtree software based on this alignment file.
then this tree ( T ) and the alignment ( A ) were used as input for ClonalFrameML analysis.
then the filtered.fasta ( F ) alignment was outputed.
My question is how to contructed a new whole genome alignment ( A' ) with only the filtered SNPs from the filtered fasta file and the same length as the first whole genome alignment ( A ), can this function be added in ClonalFrameML command.
Thanks very much!!

**Comment by xavierdidelot** [comment]
Hi Liu,

If you want A' to have the same length as A then I guess you will want to mask the recombinant sites, for example using Ns. This should be fairly easy to do based on the location of the recombination events contained in the file with suffix test.out.importation_status.txt but I'm afraid this function is unlikely to be added to ClonalFrameML as development is no longer active.

Best wishes,
Xavier
