### ISSUE TITLE
Script cfml_results.R not found

### ISSUE THREAD

**Issue by tbazilegith** [xavierdidelot/ClonalFrameML#145]
Hi Xavier,
I used the address below to find the script
https://clonalframeml.googlecode.com/svn/trunk/src/cfml_results.R
However, I got this
The requested URL /svn/trunk/src/cfml_results.R was not found on this server. That’s all we know.
Any ideas?

Thanks,
TJ

**Comment by xavierdidelot** [comment]
This script is here:
https://github.com/xavierdidelot/ClonalFrameML/blob/master/src/cfml_results.R

**Comment by tbazilegith** [comment]
Thanks!

**Comment by tbazilegith** [comment]
Hi Xavier,
My tree in the pdf file only shows some genomes. Some genomes do not display while their branches seem to be there.
Any ideas?
Thanks
________________________________

**Comment by xavierdidelot** [comment]
Sometimes labels are not shown if they are too long, you will have to edit the script to solve this or add the labels separately.
