### ISSUE TITLE
Some genomes not displaying on tree

### ISSUE THREAD

**Issue by tbazilegith** [xavierdidelot/ClonalFrameML#146]
Hi Xavier,
After running the script cfml_results.R, I noticed that some genomes do not display on tree while their branches seem to be there. I saw on previous post that the warning wouldn't a problem, but wonder why only certain genomes display. For I have 86 genomes.
Any ideas about that?
Warning message:
In ifelse(is.na(as.numeric(rownames(wh.mut))), rownames(wh.mut),  :
  NAs introduced by coercion
null device
          1
[[1]]
NULL

[[2]]
NULL
...
[[84]]
NULL

[[85]]
NULL

null device
          1

Thanks,
TJ

**Comment by xavierdidelot** [comment]
Sometimes labels are not shown if they are too long, so that there is no space for them.
You will have to edit the script to solve this or add the labels separately.

**Comment by tbazilegith** [comment]
Thanks! I work on that. 
Also, when I notice recombination on a branch such as  long dark blue line, how do I correct that?
Thanks again

**Comment by xavierdidelot** [comment]
This is already corrected in the ClonalFrameML output tree.

**Comment by tbazilegith** [comment]
Perfect! So that means the tree topology reflects the correction?

**Comment by xavierdidelot** [comment]
The branch lengths are corrected. ClonalFrameML does not change the tree topology.

**Comment by tbazilegith** [comment]
Thanks!
