### ISSUE TITLE
how to create the msa file for fragmented genomes

### ISSUE THREAD

**Issue by jianshu93** [xavierdidelot/ClonalFrameML#147]
Dear ClonalFrameML team,

I my case, my closely related genomes are not in just one piece (linear) but in several pieces because they were from mix sequencing (many other species also in the sample) or not enough coverage to assembly the genome into just one single long piece. How do I generate the msa fasta file as input to ClobalFrameML? I guess I have to use the XMFA format?

Thanks,

Jianshu

**Comment by xavierdidelot** [comment]
Hi Jianshu,

If you have only a few pieces and that together they cover most of a reference genome, then you could use this reference genome to order the pieces and leave gaps between pieces. But if you have many pieces and/or that they only cover less than say 75% of a reference genome then you should indeed create a xmfa input file which includes each piece separately. See other closed issues on the matter.

Best wishes,
Xavier
