### ISSUE TITLE
nonrecombinant alignment output empty

### ISSUE THREAD

**Issue by lagphase** [xavierdidelot/ClonalFrameML#149]
Hello,

I have ran the command 

`ClonalFrameML ALL.raxml.supportTBE snp-aln.fasta clonal.output  -kappa 0.2363 -emsim 100 -output_filtered true`

Everything worked fine, I have all the outputs including the nonrecombinant tree except that the file filtered.fasta is an empty alignment - it has the sequence identity starting with > but not the sequences.

I don't know what went wrong.....

**Comment by xavierdidelot** [comment]
I think this would only happen if there is not a single site that is not recombining in at least one of the branches. You could check this in the file that ends with .importation_status.txt
