### ISSUE TITLE
What do you mean I don't understand the output file

### ISSUE THREAD

**Issue by 17863952296** [xavierdidelot/ClonalFrameML#150]
I have been looking at the output files for 4  days, respectively: ML_sequence.fasta；position_cross_reference.txt；em.txt；importation_status.txt.
Even though I read the use guide, I still don't understand what the values in the file represent. Could you please help me explain in detail?
Why do I see in the literature that people use this software to figure out how many recombination events come from within lineages, how many recombination events come from between lineages, and how many recombination events come from outside the genome? How do you calculate this? You can even figure out who is the donor and who is the recipient in recombination events that come from between lineages.
The picture below is from the literature:
![mbio 02781-21-sf002 (1)](https://github.com/xavierdidelot/ClonalFrameML/assets/74886840/f4a20f8d-fe8a-43c7-a77e-9de61c998a98)

**Comment by xavierdidelot** [comment]
You are correct, ClonalFrameML does not say anything about where the recombination events come from. If you want to do such an analysis, you will need to extract each imported segment and assess its origin using a postprocessing step which is not part of ClonalFrameML. This should be explained in the papers you mentioned.
