### ISSUE TITLE
option -fasta_file_list true?

### ISSUE THREAD

**Issue by goshng** [xavierdidelot/ClonalFrameML#152]
Hi,

I want to use -fasta_file_list opton because I have three alignment files in FASTA format: l1.fa, l2.fa, and l3.fa, and want to use them as blocks in ClonalFrameML. File `l.txt` has a line: l1.fa l2.fa l3.fa.

```
ClonalFrameML tree.nwk l.txt cf_l -fasta_file_list true

ClonalFrameML v1.13
fasta_file_list = true
Finished reading in control file.

ERROR: could not find listed file l.txt
```

I've attached a compressed file with the files that I tested. I tried the source code version and conda package version, and either produced the same error.

```
$ ls
l1.fa  l2.fa  l3.fa  l.txt  run  run.log  tree.nwk

```

Did I misunderstand the usage of the option -fasta_file_list?

Thank you,
SangChul

[t.tar.gz](https://github.com/xavierdidelot/ClonalFrameML/files/15383430/t.tar.gz)

**Comment by xavierdidelot** [comment]
The fasta_file_list option is useful if you have each single sequence in a separate fasta file. But what you have here is separate alignments of genes in each fasta file. To handle this, ClonalFrameML needs you to first put all the genes in a XMFA file and then use the xmfa_file option:
``cat l1.fa > l.xmfa;echo = >> l.xmfa;cat l2.fa>>l.xmfa;echo = >> l.xmfa;cat l3.fa>>l.xmfa;echo = >> l.xmfa``
Then you should run
``ClonalFrameML tree.nwk l.xmfa cf_l -xmfa_file true``
