### ISSUE TITLE
Segmentation fault after reading tree

### ISSUE THREAD

**Issue by xonq** [xavierdidelot/ClonalFrameML#153]
I am running into an ambiguous segmentation fault during or directly following reading the newick file. 

The alignment is directly from ProgressiveMauve output. The phylogeny is generated from IQ-TREE2. I removed bootstrap values from the newick and converted the tip names to correspond to the XMFA headers.

output:
```
ClonalFrameML v1.13
xmfa_file = true
Finished reading in control file.

Read 55 sequences of length 9513468 sites from mauve.xmfa
/var/spool/slurmd/job29499047/slurm_script: line 12: 117246 Segmentation fault      (core dumped) ~/software/ClonalFrameML/src/ClonalFrameML final.phylo.newick mauve.xmfa clonalframe.huh -xmfa_file true
```

command:
```bash
~/software/ClonalFrameML/src/ClonalFrameML final.phylo.newick \
mauve.xmfa clonalframe.huh -xmfa_file true
```

input files:
[mauve.xmfa](https://drive.google.com/file/d/1cleBstG_-EbDYoyi7t_hjyOmIE3vVTXN/view?usp=sharing)
[final.phylo.newick](https://drive.google.com/file/d/1m3asqd0bO0dMe2wlxvmwd5WccjxJDLt9/view?usp=sharing)

**Comment by xavierdidelot** [comment]
You can't run ClonalFrameML directly on the output of Mauve. You need to first extract the core of the alignment, ie the regions that are shared by all genomes. There is a tool to do exactly that in the Mauve suite called stripsubsetLCBs. Cf issue #29 where I gave links to it, but these seem to now be broken. I don't know if stripsubsetLCBs is still available or if there is something else you could use to do the same.

**Comment by xonq** [comment]
Thank you for your response, I can confirm `stripSubsetLCBs` is part of the `mauveAlign` package and I was able to get ClonalFrameML working.
