### ISSUE TITLE
N/A on posterior means on the per branch model

### ISSUE THREAD

**Issue by PaulineGachanja** [xavierdidelot/ClonalFrameML#154]
Hello,
I am running ClonaFrameMl on 17 fungi samples. However, on the per-branch model, I am getting the posterior means and variance as N/A. Should I trust the rest of the results? Or what could be the problem?

Parameter       Branch  Posterior Mean  Posterior Variance      a_post  b_post
R/theta Mean    4.10437 NA      NA      NA
1/delta Mean    0.0072958       NA      NA      NA
nu      Mean    0.11986 NA      NA      NA
M       Mean    0.000351216     NA      NA      NA

Looking forward to your reply.
Thanks.

**Comment by xavierdidelot** [comment]
Yes that is normal behaviour and you can trust the remainder of the file. When using the per-branch model, only the mean is returned on these four lines, and these act as multipliers for the per-branch values . See also issue #114

**Comment by PaulineGachanja** [comment]
Thank you so much for the quick reply.
