### ISSUE TITLE
ERROR: Number of nodes in Newick tree inconsistent with that expected

### ISSUE THREAD

**Issue by xonq** [xavierdidelot/ClonalFrameML#156]
Having a hard time understanding this error. I removed any polytomies, and rooted the tree. Please advise if this is a problem on my end:

```ClonalFrameML v1.13
xmfa_file = true
emsim = 100
label_uncorrected_tree = true
Finished reading in control file.

Read 73 sequences of length 5324418 sites from core.nopoly.xmfa
ERROR: Number of nodes in Newick tree inconsistent with that expected
```

Command:
```
~/software/ClonalFrameML/src/ClonalFrameML no_polytoms.newick \
core.nopoly.xmfa cf_out -xmfa_file true -emsim 100 -label_uncorrected_tree true
```

[newick](https://drive.google.com/file/d/1TyjW0BobZX_M2QMylD_7IunQbe4Zgb8Y/view?usp=sharing)

[core xmfa](https://drive.google.com/file/d/1oQ3FknE31hYanjzDE-Hn7yKxBg0ozp16/view?usp=sharing)

**Comment by xavierdidelot** [comment]
I have just requested access to your files on Google Drive so I can try and replicate the error on my side.

**Comment by xavierdidelot** [comment]
There are 73 sequences in your xmfa file, but only 72 leaves in your tree.

**Comment by xonq** [comment]
Hello Xavier, thanks for your reply - Unfortunately, this doesn't resolve the issue. ClonalFrame is reporting there are 73 sequences in the XMFA, but I'm only detecting 72 (note I removed 2 entries thinking polytomies may be the issue, so the comment header is incorrect). all 72 overlap with the newick tips.

**Comment by xavierdidelot** [comment]
There are 145927 header lines (starting with >) and 1999 gene blocks (ending with =), so 145927/1999=73 sequences.

**Comment by xonq** [comment]
`grep -Po "^> [^:]+" core.nopoly.xmfa | sort | uniq | wc -l` shows 72, upon closer inspection, one of the sequence IDs (xancam23) was duplicated. I apologize for taking your time. Thank you.
