### ISSUE TITLE
Newick tree tip label 1.000000 was not expected

### ISSUE THREAD

**Issue by danknight** [xavierdidelot/ClonalFrameML#17]
Dear Xavier/Daniel,

I am having difficulty with running ClonalframeML. I have the appropriate input files e.g. a starting tree (.txt) in Newick format generated by phyml and an alignment of the sequences in fasta format.

When i run the command 
 ./ClonalframeML /home/SNV1.txt /home/SNV1.fa SNV1_out

I get the following error

ClonalFrameML version 1.25
Finished reading in control file.

Read 20 sequences of length 4290252 sites from /home/SNV1.fa
ERROR: convert_NewickTree_to_marginal_tree(): Newick tree tip label 1.000000 was not expected

I did see that someone else had this error (#7) and that is was resolved offline.
Please can you advise.

Best wishes
Daniel

**Comment by xavierdidelot** [comment]
Dear Daniel,

This error message means that you have bootstrap values in your newick file that need to be removed. You can remove them using the following perl one liner:
perl -i.bk -wpe's/\)[0-9\.]*:/):/g' /home/SNV1.txt 

Best wishes,
Xavier

**Comment by danknight** [comment]
Thanks for the super-fast reply!

**Comment by simianraticus** [comment]
Dear Xavier,

I am experiencing a similar issue, but apparently is more closely related to the one reported previously (#7) and resolved offline. 

I run the command:
./ClonalFrameML /home/prova1.nwk /home/prova1.xmfa /home/prova1_out -xmfa_file true -show_progress true

but I get the following error:

"ClonalFrameML version 1.-178
xmfa_file = true
show_progress = true
Finished reading in control file.

Read 6 sequences of length 2844495 sites from /home/prova1.xmfa
ERROR: convert_NewickTree_to_marginal_tree(): Newick tree tip label seq5 was not expected"

Could you please help me to resolve this?

All the best


Ed

**Comment by xavierdidelot** [comment]
Hi Ed,

You should make sure that the header lines of your XMFA file are formatted
for example as follows:
>seq5
In particular nothing is allowed after the "seq5" (as there would be if
your xmfa is the output of mauve for example) and no space is allowed after
the ">" symbol.

Best wishes,
Xavier

**Comment by saadleeshehreen** [comment]
Dear Xavier,
I am having difficulties running ClonalFrameML. I aligned my sequences with progressivaMauve. That software generates .xmfa and .tree files.  According to that software, the tree is the standard Newick tree file format. I changed the file extension to .phyML.newick from .tree. But converted the .xmfa to .fasta as ClonalFrameML produced error message. Then run the following command: 

/.clonalFrameML my_seqs.phyML.newick t2.fasta my_seqs.out 

But got the following error message:

"Numbers of nodes in Newick tree inconsistent with that expected."

Do you have any suggestions about generating two input files? Which software can I use rather progressiveMauve? 
 
Cheers

**Comment by xavierdidelot** [comment]
The recommended method for building the alignment is to use reference mapping, for example BWA, SMALT, Bowtie or Stampy. Or if you only have your genomes as de novo assembled contigs, you could use MUMMER to align them all one by one against a reference genome.
