### ISSUE TITLE
ERROR: convert_NewickTree_to_marginal_tree

### ISSUE THREAD

**Issue by simianraticus** [xavierdidelot/ClonalFrameML#18]
Dear Xavier,

I am experiencing an issue that apparently is closely related to two athers reported previously (#7, #17), but the solution does not seem to apply to my situation.

I am trying to perform a recombination analysis on 6 bacterial genomes. The two input files provided to the software are an xmfa alignment and a guide tree in Newick format, both constructed with MAUVE. 

I run the command:
./ClonalFrameML /home/prova1.nwk /home/prova1.xmfa /home/prova1_out -xmfa_file true -show_progress true

but I get the following error:

"ClonalFrameML version 1.-178
xmfa_file = true
show_progress = true
Finished reading in control file.

Read 6 sequences of length 2844495 sites from /home/prova1.xmfa
ERROR: convert_NewickTree_to_marginal_tree(): Newick tree tip label seq5 was not expected"

I have tried to edit the Newick file to change or remove tip labels, but that did not change the situation.

Could you please help me to resolve this?

All the best

Ed

P.S. sorry for the double post, but I have just noticed that the original one was posted by mistake as a reply to the closed Issue #17.

**Comment by xavierdidelot** [comment]
Hi Ed,

You should make sure that the header lines of your XMFA file are formatted
for example as follows:
>seq5
In particular nothing is allowed after the "seq5" (as there would be if
your xmfa is the output of mauve for example) and no space is allowed after
the ">" symbol.

Best wishes,
Xavier

**Comment by simianraticus** [comment]
Hi Xavier,

Thank you for your fast reply!

I have changed the headers in the xmfa file as you specified in your reply and apparently it worked fine to overcome the reported error.

Unfortunately after few seconds I got a new error... :(

I run the command:

./ClonalFrameML /home/prova1.nwk /home/prova1_edit.xmfa /home/prova1_out -xmfa_file true -show_progress true

but I get the following error:

"ClonalFrameML version 1.-178
xmfa_file = true
show_progress = true
Finished reading in control file.

Read 6 sequences of length 2844495 sites from /home/prova1_edit.xmfa
ERROR: FASTA_to_nucleotide(): unsupported base

Would you please help me again on this?

More specifically it would be great if you explained me which mauve .xmfa file characteristics need modification before a ClonalFrameML run.

Thank you very much!

All the best,


Ed

**Comment by xavierdidelot** [comment]
Hi Ed,

The character 'N' is the only one allowed to represent ambiguous bases. Can
you check you don't use some other character somewhere? None of the other
symbols are accepted from the list at
http://www.chick.manchester.ac.uk/SiteSeer/IUPAC_codes.html

Best wishes,
Xavier

**Comment by simianraticus** [comment]
Hi Xavier,

I have performed a search for 'illegal' nucleotide characters in my modified xmfa file, but, besides '-' for gaps or '=' for comments, I could not find any.

Since I have just noticed that the mauve xmfa file has lower case characters to represent nucleotides, I wonder if ClonalFrameML is case sensitive in nucleotide recognition.

Otherwise I cannot figure out what could be the problem here.

Thank you a lot again.

All the best,

Ed

**Comment by xavierdidelot** [comment]
No it's definitely not case sensitive. There must be something in file that
CFML does not like. Could you send it to me or at least some extract so I
can reproduce your problem?
Xavier

**Comment by simianraticus** [comment]
Thank you, I have just sent you the file by email.

**Comment by xavierdidelot** [comment]
For the record, the xmfa file was not valid input for CFML because all alignment blocks need to have sequence for all genomes. The first block had seq1, seq2, seq3, seq4, seq5, seq6 but the second block had only seq2, seq3, seq6. etc.
