### ISSUE TITLE
importation_status.txt to be in BED format

### ISSUE THREAD

**Issue by alexjironkin** [xavierdidelot/ClonalFrameML#20]
Can this output be in proper BED format? It would be really useful to use in othertools as well.

I think the only thing missing is **chr** value to be the first column, instead of sample/internal branch.

So instead of:

```
    Node       Beginning      End
    NODE_12    12              1234
    SAMPLE1    1235            1245
```

We get

```
    chr    12                 1234    NODE_12
    chr    1235               1245    SAMPLE1
```

Perhaps the same of the **chr** can be supplied to the command line?

**Comment by xavierdidelot** [comment]
Thanks for the suggestion. Export of the recombination events is now supported in BED format. This option is activated using the argument "-chromosome_name" followed by the name of chromosome to use in the first column of the BED file, for example "-chromosome_name chr". If this argument is not used, the old recombination format is used for backward compatibility.

**Comment by alexjironkin** [comment]
Just noticed this after compiling and running on a dataset we had, BED files generally don't have header line. So bedtools complained about the header line. Can we remove it for BED output only? I can create another pull request if you want.

**Comment by xavierdidelot** [comment]
Done (-:
Xavier
