### ISSUE TITLE
Removing root in labelled_tree.newick

### ISSUE THREAD

**Issue by danknight** [xavierdidelot/ClonalFrameML#23]
Hi,

After running clonalframeML with default options I would like to compare the output tree (labelled_tree.newick) with the input tree (RAxML.newick) to see how the program has altered the topology and branch lengths (if at all). 

Only when I open in a tree viewer like MEGA I see that the clonalframeML tree is rooted and the layout is quite different from the input tree and a little confusing to read. I ideally need mid-point roots (or at least the option to add and remove myself). My question is how can I unroot the output tree to allow for a sensible comparison? Was there a flag to pass during invoking clonalframeML? 

I hope this makes sense. I have attached the input and output trees (appended with .txt to allow attaching to this message)

Input tree (RAxML)
[RAxML_bestTree.cd-raxml-8.nwk.txt](https://github.com/xavierdidelot/ClonalFrameML/files/137331/RAxML_bestTree.cd-raxml-8.nwk.txt)
.
Output tree (ClonalframeML)
[gethoms4_cd-raxml-8_cfml.labelled_tree.newick.txt](https://github.com/xavierdidelot/ClonalFrameML/files/137326/gethoms4_cd-raxml-8_cfml.labelled_tree.newick.txt)

Any help you can provide would be much appreciated.
Kind regards
Dan

**Comment by danny-wilson** [comment]
Midpoint root the tree before inputting it. CFML doesn't change the
topology.

BW
Danny

**Comment by danknight** [comment]
Thanks
