### ISSUE TITLE
The results for the sample data set

### ISSUE THREAD

**Issue by YangChaoCN** [xavierdidelot/ClonalFrameML#28]
Dear Xavier/Daniel,

After testing the sample data, I got the same result as GoogleCodeExporter did. 
https://github.com/xavierdidelot/ClonalFrameML/issues/16
Could you please also tell me the reason?

In addition to this, I run the following command with cfml_results_2.R in cfml.tgz.
Rscript cfml_results_2.R Exam core-sites.txt
I got the pdf Exam.cfml.pdf, but the Grey areas do not exist, is the grey areas was added later by other tool?
[Exam.cfml.pdf](https://github.com/xavierdidelot/ClonalFrameML/files/214576/Exam.cfml.pdf)

Best wishes,
YangChao

**Comment by xavierdidelot** [comment]
Dear YangChao,

I think these are the correct result for running ClonalFrameML under the default model, whereas the results reported in the paper correspond to the rho-per-branch model. Please let me know (and re-open the issue) if this is not correct.

Best wishes,
Xavier
