### ISSUE TITLE
Newick tree tip label was not expected

### ISSUE THREAD

**Issue by pjoncour** [xavierdidelot/ClonalFrameML#29]
Hi Xavier, 

I'm having some trouble running ClonalFrameML on my data. My newik tree and xmfa file have been obtained by Mauve and I'm having the same error as others : 

_Read 21 sequences of length 1063625 sites from ClonalFrame_Lp_genomes/GWAS_alignment.xmfa
ERROR: convert_NewickTree_to_marginal_tree(): Newick tree tip label seq5 was not expected_

So I followed your advice on topic #18 
and simplifyed my headers (ex :  >seq5).

But it was not enough to solve the error. 

Then I noticed the solution of topic #17, but my tree doesn't seem to have bootstrap values. 

Then going back to the end of topic #18, I noticed than in my xmfa file, as simianraticus, most of blocks doesn't have the sequence of all genomes. =/.

Did you find out a solution for that ? Would you recommand to use an other software than Mauve to produce the xmfa file and the newick tree ? 

Thank you very much for your help :)

**Comment by xavierdidelot** [comment]
Hello,

Yes you can use mauve to generate your input alignment, but you need to extract the core from it, ie the regions that are shared by all genomes. There is a tool to extract the core from an alignment, and it is
called stripsubsetLCBs.
You can download it for linux here:
http://darlinglab.org/mauve/snapshots/2015/2015-01-09/linux-x64/stripSubsetLCBs.bz2
Or for mac here:
http://darlinglab.org/mauve/snapshots/2015/2015-01-12/MacOS/stripSubsetLCBs.bz2
Or for windows here:
http://darlinglab.org/mauve/snapshots/2015/2015-02-26/windows/stripSubsetLCBs.exe

Best wishes,
Xavier

**Comment by pjoncour** [comment]
Hello Xavier, 

Thank you very much for your fast answer. I tried many things and I still have the error. 
I relaunch Mauve, extracted the core alignement (with a dedicated R script, because I couldn't make stripSubsetLCBs work). I tried with the xmfa and the fasta format. 

_Read 12 sequences of length 18368773 sites from ClonalFrame_Lp_genomes/Mauve_top_low_coreRG_12seq.fasta
ERROR: convert_NewickTree_to_marginal_tree(): Newick tree tip label seq9 was not expected_

A managed to make ClonalFrameML worked with the input files from issue #5. But not with my files ...

Do you think you can have a look to my input files ? (Extraction of 1 block attached) 
[Input_block2.txt](https://github.com/xavierdidelot/ClonalFrameML/files/223475/Input_block2.txt)
[input_tree.txt](https://github.com/xavierdidelot/ClonalFrameML/files/223478/input_tree.txt)


Thank you 
Best regards, 
Pauline

**Comment by xavierdidelot** [comment]
Dear Pauline,

ClonalFrameML works on these two files on my computer. I think you might be using an older version of ClonalFrameML, which did not support dos formatted line endings. You could try with this alignment file, in which I converted the line endings to unix format:
[converted.txt](https://github.com/xavierdidelot/ClonalFrameML/files/225553/converted.txt)
The best solution would be to update your ClonalFrameML to the latest version.

Best wishes,
Xavier

**Comment by pjoncour** [comment]
Dear Xavier, 

Thank you very much for your time ! 
That's great ! With your file it worked also for me. I'm using ClonalFrameML version 1.25. I'll see if I can update it or I'll convert the line endings of my files. 

Thank you ! 

Best wishes,

Pauline
