### ISSUE TITLE
what's the meaning of the "-embranch_dispersion"

### ISSUE THREAD

**Issue by xiaohai90** [xavierdidelot/ClonalFrameML#30]
Dear Xavier/Daniel,

As for the per-branch model, the default value of parameter "-embranch_dispersion" is 0.01, and it was set to 0.1 in the example of S. aureus. I read your paper and can't find any description about it. So could you please explain the meaning of this parameter and how would it influence the result?

Best regards!
xiaohai

**Comment by xavierdidelot** [comment]
Dear Xiahai,

This parameter determines how much variation is expected in the recombination parameters from one branch to another. A small dispersion means that we expect branches to have rather similar parameters, and if the dispersion was equal to zero this would be equivalent (at least in principle) to the default model where all branches have the same parameters. I would recommend to start running ClonalFrameML with the default (ie not per-branch) model, and if you think ClonalFrameML is being too conservative in the results then use the per-branch model first with small (eg 0.01) values of the dispersion and to increase if you think it is still too conservative.

Best wishes,
Xavier

**Comment by xiaohai90** [comment]
Dear Xavier,

Thanks for your explanation, I've got it. And I have another question. I used cfml_results.R to draw the picture. Command : Rscript cfml_results.R prefix core_position.list , and i got a pdf (see attach file)

I just wonder why there are some recombination regeion(the blue horizontal bars) across the grey region, which means the non-core sites?

Best Wishes,
xiaohai

**Comment by xavierdidelot** [comment]
Dear Xiaohai,

If a recombinant region stretches across a non-core region, it means that ClonalFrameML has inferred recombination both upstream and downstream from the non-core region, and that the non-core region is small enough (relative to the average length of recombination delta) for the recombination event to be most likely to stretch across the non-core region.

Best wishes,
Xavier
