### ISSUE TITLE
clonalframeml fails to compile

### ISSUE THREAD

**Issue by jpearl01** [xavierdidelot/ClonalFrameML#32]
Hello,
Just trying to compile this on a fedora 19 desktop and running into this error after I run 'make': 

/bin/echo "#define ClonalFrameML_GITRevision \"`git describe --tags`\"" > version.h
g++ -O3 -I./ -I./myutils -I./coalesce -c -o main.o main.cpp
In file included from coalesce/coalesce.h:22:0,
                 from main.h:25,
                 from main.cpp:20:
./coalesce/coalescent_control.h: In member function ‘Control& Control::read_input(char*)’:
./coalesce/coalescent_control.h:121:87: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    if(!control_file.got_required)error("Not all necessary items found in control file");
                                                                                       ^
./coalesce/coalescent_control.h:124:85: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   if(!control_file.got_required)error("read_input(): necessary parameters not found");
                                                                                     ^
./coalesce/coalescent_control.h:128:69: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   if(ntimes.size()!=nsamp)error("ntimes inconsistent in size with n");
                                                                     ^
./coalesce/coalescent_control.h:135:65: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   if(len.size()!=loci)error("len inconsistent in size with loci");
                                                                 ^
./coalesce/coalescent_control.h:136:87: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   if(state_freq.size()!=n_states)error("state_freq inconsistent in size with n_states");
                                                                                       ^
./coalesce/coalescent_control.h:144:81: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   else if(seq_len!=ind_seq_len) error("seq_len and the sum of len do not equate");
                                                                                 ^
./coalesce/coalescent_control.h:159:92: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   if(!one_or_the_other)error("read_input(): neither state_M or state_rel_mut_rate received");
                                                                                            ^
./coalesce/coalescent_control.h:162:82: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    if(state_M.size()!=n_states)error("state_M inconsistent in size with n_states");
                                                                                  ^
./coalesce/coalescent_control.h:170:104: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    if(state_rel_mut_rate.size()!=n_states)error("state_rel_mut_rate inconsistent in size with n_states");
                                                                                                        ^
./coalesce/coalescent_control.h: In member function ‘Control& Control::vector_to_Matrix(std::vector<double>*, myutils::Matrix<double>*, int, int)’:
./coalesce/coalescent_control.h:202:94: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   if((int)vec->size()<(rows*cols))error("vector_to_Matrix(): vector too small to fill matrix");
                                                                                              ^
./coalesce/coalescent_control.h:203:93: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   if((int)vec->size()>(rows*cols))error("vector_to_Matrix(): vector too large to fit matrix");
                                                                                             ^
./coalesce/coalescent_control.h: In member function ‘Control& Control::read_mut_matrix(myutils::Matrix<double>&, std::vector<double>&)’:
./coalesce/coalescent_control.h:224:73: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   if(G.nrows()!=G.ncols())error("read_mut_matrix(): not a square matrix");
                                                                         ^
./coalesce/coalescent_control.h:231:72: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
      if(G[i][j]<0.0)error("read_mut_matrix(): negative rates in matrix");
                                                                        ^
./coalesce/coalescent_control.h:234:69: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    if(rowsum!=-G[i][i]) error("read_mut_matrix(): not a rate matrix");
                                                                     ^
./coalesce/coalescent_control.h:239:83: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   if(pi.size()!=n_states)error("read_mut_matrix(): pi inconsistent in size with G");
                                                                                   ^
./coalesce/coalescent_control.h:243:76: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    if(pi[i]<0.0)error("read_mut_matrix(): negative equilibrium frequencies");
                                                                            ^
./coalesce/coalescent_control.h:246:66: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   if(pisum!=1.0)error("read_mut_matrix(): pi does not sum to one");
                                                                  ^
In file included from ./coalesce/coalescent_process.h:35:0,
                 from coalesce/coalesce.h:23,
                 from main.h:25,
                 from main.cpp:20:
./coalesce/coalescent_record.h: In member function ‘mt_node* marginal_tree::coalesce(double&, int&, int&)’:
./coalesce/coalescent_record.h:119:58: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    error("coalesce(): cannot coalesce a node with itself");
                                                          ^
./coalesce/coalescent_record.h:126:57: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    error("coalesce(): called when no longer segregating");
                                                         ^
./coalesce/coalescent_record.h: In member function ‘mt_node* marginal_tree::migrate_coalesce(double&, int&, int&)’:
./coalesce/coalescent_record.h:148:58: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    error("coalesce(): cannot coalesce a node with itself");
                                                          ^
./coalesce/coalescent_record.h:155:57: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    error("coalesce(): called when no longer segregating");
                                                         ^
g++  -o ClonalFrameML main.o

Any ideas what is going on? 
Thanks!
~josh

**Comment by xavierdidelot** [comment]
Hi Josh,

Are you sure it did not work? Can you see the executable file called "ClonalFrameML"? If so it means it did compile successfully. You can safely ignore all these warnings, and I can't see an error message in there.

Best wishes,
Xavier

**Comment by jpearl01** [comment]
Hey Xavier,

As soon as I sent that I realized that I hadn't actually checked if there was an executable and there definitely is.  I also got it to compile on a Centos 6.7 machine as well, so I think I should be good, thanks!

~josh

**Comment by xavierdidelot** [comment]
Great! (-:
