### ISSUE TITLE
core.xmfa file from stripsubsetsLCB header needs reformatting

### ISSUE THREAD

**Issue by hoytpr** [xavierdidelot/ClonalFrameML#33]
To get an XMFA file that works in ClonalFrame, the original XMFA output from MAUVE will not work. After running StripsubsetsLCB as described [here](https://github.com/xavierdidelot/ClonalOrigin/wiki/Usage) the StripsubsetsLCB output XMFA file (originally from MAUVE) has the correct lengths format, but the header lines often have additional information such as genome position numbers that must be removed, leaving only the organism name (e.g. >S. aureus). 
Below is a short script to remove the genome position numbers up to the organism name, *if and ONLY if*, your headers look like mine (for example):

>  \>2:3289121-3291310 + e.anophelisNUHP1.fas

sed can be used on the StripsubsetsLCB output XMFA file:
`sed -r 's/^>..* -*/>/' your_xmfa_file.xmfa`
I'm not a great coder so please improve on this one-liner. It seems to work for me but doesn't have any fail safes and I'm running Python in a bash console on Windows 10 (not the built-in Ubuntu yet).

 pete

**Comment by xavierdidelot** [comment]
Thanks Pete!
Here's another solution, using perl:
`perl -i.bk -wpe's/^>..* -*/>/' your_xmfa_file.xmfa`

Best wishes,
Xavier

**Comment by hoytpr** [comment]
Actually, just using
   sed -r 's/^>.* />/' your_xmfa_file.xmfa 
seems to work just as well.
