### ISSUE TITLE
Error newick tree: Too few right brackets

### ISSUE THREAD

**Issue by Yavapai13** [xavierdidelot/ClonalFrameML#34]
Hi Xavier,

I'm having problems to run ClonalFrameML ( v1.0-19-g9488a80) on my data...

I generated the alignment file with mauve, so I'm using the .xmfa file as an input by adding the option "-xmfa_file true". The tree file looks like this: (sample1,((sample2,sample3),sample4));. The names in the headers of the alignment file match the ones in the tree. After executing the command, I get the following error message:

ERROR: Token: sample1,((sample2,sample3
Too few right brackets

I've followed different advises found along the comments here but nothing seems to work: I'm using the core alignment, there are no white spaces after the ">", I converted the end lines, I also tried to work with a concat fasta file... What else can I do? I'm running out of ideas...

Thanks for you help!

/Andrea

**Comment by xavierdidelot** [comment]
Hi Andrea,

Your input tree needs to have branch lengths included, so should look like this:
(sample1:0.001,((sample2:0.001,sample3:0.002):0.001,sample4):0.002);

ClonalFrameML will correct these branch lengths so they do not have to be very accurate, but they have to be there anyway.

Best wishes,
Xavier

**Comment by Yavapai13** [comment]
Great, it worked! I had tried it before but maybe I still needed more adjustments at some other point... 

Thanks a lot!!!

Andrea
