### ISSUE TITLE
how is labelled_tree.newick constructed?

### ISSUE THREAD

**Issue by YangChaoCN** [xavierdidelot/ClonalFrameML#35]
Dear Xavier,

I want to know how the labelled_tree.newick is constructed, is the recombination region in importation_status.txt removed and then the rest region was used  to reconstruct the tree?

If I want to use SNPs in non-recombinant regions to reconstruct tree, what should I do? 
Is it right? 1.remove the recombination region in importation_status.txt. 2.call SNPs in the rest region. 3. reconstruct phylogenetic tree

Best regards, 
Yangchao

**Comment by xavierdidelot** [comment]
Hi YangChao,

The tree you get out of ClonalFrameML is not the same as the tree you would get by removing the recombinant regions. 

The lengths of the branches in the ClonalFrameML output tree take into account both mutation and recombination events that have been found on that branch. If a lot of recombination events have been detected on a given branch, excluding all these regions would result in a very short branch, but not so in ClonalFrameML, and indeed if we see a lot of recombination events it must mean that a significant amount of evolution has taken place and so the branch can't be that short. 

Also, excluding recombinant regions before building the tree would mean that recombination regions are excluded for all branches. So if you have that all sites are recombinant on at least one branch, you would be left with nothing to build your tree, whereas ClonalFrameML accounts for recombination and the branches where they were inferred. 

If you really want to build a tree based on only the non-recombinant regions then you can excluded the regions in importation_status and build a tree from the remainder, but for the reasons described above the ClonalFrameML output tree should be closer to the truth.

Best wishes,
Xavier

**Comment by YangChaoCN** [comment]
Hi Xavier,

If ClonalFrameML output tree take into account both mutation and recombination events, how  to calculate the length of each branch?   For example, we see 10 SNPs in a branch, 5 SNPs was introduced by 5 mutations, the other 5 SNPs were introduced by 1 recombination. In the ClonalFrameML output tree, how many SNPs would present? how to correct branch length in ClonalFrameML?

Best wishes,

**Comment by xavierdidelot** [comment]
The length of each branch is calculated as a function of the number of mutation and recombination events found on that branch, and the rates at which mutation and recombination events happen. Cf the ClonalFrameML paper for a more exact description.

**Comment by YangChaoCN** [comment]
Thank you so much.
