### ISSUE TITLE
Warning message: NAs introduced by coercion

### ISSUE THREAD

**Issue by hoytpr** [xavierdidelot/ClonalFrameML#38]
We've run ClonalFrameML through the 
      `ClonalFrameML newick_file seq_file output_prefix [OPTIONS]`
step, getting the appropriate output files. However running 

`Rscript.exe cfml_results.R anophelisoutbreakclone2.output` 

gives the following errors:

>  Read 3918024 items
> Read 30 items
> Warning message:
> NAs introduced by coercion
> Warning message:
> In ifelse(is.na(as.numeric(tree$tip.label)), tree$tip.label, paste("C0000",  :
>   NAs introduced by coercion
> Warning message:
> In ifelse(is.na(as.numeric(rownames(wh.mut))), rownames(wh.mut),  :
>   NAs introduced by coercion
> Error in pdf(file = "/dev/null", width = 14, height = 7) :
>   cannot open file '/dev/null'
> Execution halted

We are running R-3.2.5 64-bit on a 64-bit Windows 10 machine with the latest ape and phangorn loaded. Searching turned up nothing except it involves the `as.numeric` function. 

Also, if problem is with running a Windows machine, let me know. Thanks.
Peter

**Comment by xavierdidelot** [comment]
Hi Peter,

This problem is specific to Windows and should not happen again if you try again on a Linux or Mac machine. Sorry for the hassle!

Best wishes,
Xavier
