### ISSUE TITLE
Fasta sequence used for labelled_tree.nwk

### ISSUE THREAD

**Issue by Stan-walker** [xavierdidelot/ClonalFrameML#40]
Dear Dr Didelot

From reading issue #35, I understand that the  labelled_tree.nwk is not created from simply removing all recombination, but rather takes into account both mutation and recombination. Can I obtain the sequence fasta that CFML has used to create this phylogeny?
I would like to use BEAST, and therefore adjust my MSA to account for recombination.

Kind regards

Stan

**Comment by xavierdidelot** [comment]
Hi Stan,

As you wrote the CFML output tree is not created by removing recombinant regions and computing a tree, so it is not really possible to extract positions that would give you the same tree. If you want to extract a recombinant-free alignment for example to use in BEAST then you can do so by removing from your alignment all positions tagged as recombinant in the importation_status.txt output file. If there is not a lot of recombination overall then this approach will be fine and should give you something similar to the CFML output tree. But if there has been a lot of recombination then this approach will not work very well (you might even be left with no sites at all!)

Best wishes,
Xavier
