### ISSUE TITLE
Newick tree tip label was not expected

### ISSUE THREAD

**Issue by juliofdiaz** [xavierdidelot/ClonalFrameML#42]
Dear Xavier,
I am running into some problems while running ClonalFrameML. I used as input an alignment in the standard fasta format. I used this file to create a tree using RaxML in Galaxy. I then run the software as
`$ /Software/clonalframeml-read-only/src/ClonalFrameML CF170_RaxML-Chr3.nwk CF170_orderedSNPAlignment_Chr3.fa chr3.output > chr3.log.txt`

[alignmentInFasta.txt](https://github.com/xavierdidelot/ClonalFrameML/files/363058/alignmentInFasta.txt)
[RaxML_Newick.txt](https://github.com/xavierdidelot/ClonalFrameML/files/363059/RaxML_Newick.txt)

However, I run into the following error:
```
ClonalFrameML version 1.-178
Finished reading in control file.

Read 111 sequences of length 177 sites from CF170_orderedSNPAlignment_Chr3.fa
ERROR: convert_NewickTree_to_marginal_tree(): Newick tree tip label 2 was not expected
```
I was not expecting this error since I created the tree with the same fasta I'm using for ClonalFrameML. I saw that in a [previous post](https://github.com/xavierdidelot/ClonalFrameML/issues/17) you suggested removing the bootstrap values, which I tried but that does not seem to be the problem. Could you please help me with this problem?

I have an additional question. This dataset includes only the polymorphic sties from the entire genomes of intraclonal bacteria (meaning I don't expect any genomic rearrangements amongst these genomes). Is this data appropriate as input for CFML? I am just wondering about this since the relative distance between the polymorphic sites are not input.

Thanks in advance for your time.
Julio Diaz Caballero

**Comment by xavierdidelot** [comment]
Dear Julio,

I had no problem at all running ClonalFrameML on your files on my side. I think you might be using an older version of ClonalFrameML, could you please update to the latest github version and let me know if it still does not work.

Best wishes,
Xavier

**Comment by juliofdiaz** [comment]
Thanks! I had downloaded the source from the link in the manual http://www.danielwilson.me.uk/ClonalFrameML/ClonalFrameML-sourcecode.zip. So instead I used the git alternative and it worked.

I have an additional question. My dataset includes only the polymorphic sites from the entire genomes of intraclonal bacteria (meaning I don't expect any genomic rearrangements amongst these genomes). Is this data appropriate as input for CFML? I am just wondering about this since the relative distance between the polymorphic sites are not input.

Thanks again for your time.
Julio DC

**Comment by xavierdidelot** [comment]
Hi Julio,

No it's not appropriate to use a concatenation of polymorphic sites only. Your input should include the non-polymorphic sites, because ClonalFrameML needs to know the distance between polymorphic sites to assess the probability of recombination between them.

Best wishes,
Xavier

**Comment by juliofdiaz** [comment]
Thanks, Im including the additional sites.
