### ISSUE TITLE
problem with newick file from parsnp output

### ISSUE THREAD

**Issue by plasmid02** [xavierdidelot/ClonalFrameML#43]
using Clonal Frame 1.7 and trying to run directly from the output of parsnp, which produces a tree and multifasta file of the aligned genomes. I get an error, which looks like the program is having trouble reading the tree:

`$ ClonalFrameML parsnp.tree parsnp.fasta output -kappa 2
ClonalFrameML version 1.7
kappa = 2
Finished reading in control file.

Read 526 sequences of length 2233330 sites from parsnp.fasta
ERROR: convert_NewickTree_to_marginal_tree(): Newick tree tip label 0.920 was not expected`

There are no tip labels with this name but there are internal branch lengths.  Interested to know if anyone else has seen this?

**Comment by xavierdidelot** [comment]
Hi Tim! 
Could you please try again with the latest version of ClonalFrameML from github? 
Thanks, Xavier

**Comment by plasmid02** [comment]
Thanks Xavier! program seems to be running OK tho it may take a fair while
to process. I was using the homebrew version.

Tim

**Comment by xavierdidelot** [comment]
Thanks Tim. I'll see what needs to be done to have the homebrew version updated to the latest version.
Xavier
