### ISSUE TITLE
cmfl_results.R script error

### ISSUE THREAD

**Issue by slhogle** [xavierdidelot/ClonalFrameML#44]
Hi, 

the cfml_results.R script is throwing an error, and I'm having a difficult time figuring out how to resolve it. I've attached the CFML output files that I'm feeding into the script. I'm using R v3.3.0, ape v3.5, and phangorn v2.0.4. Thanks in advance for your help and the useful software!

best,
shane

> Warning message:
  NAs introduced by coercion 
  Warning message:
  In ifelse(is.na(as.numeric(rownames(wh.mut))), rownames(wh.mut),  :
  NAs introduced by coercion
Warning message:
In ifelse(is.na(as.numeric(rownames(wh.mut))), rownames(wh.mut),  :
  NAs introduced by coercion
null device 
          1 
[[1]]
NULL
[[2]]
NULL
[[3]]
NULL
[[4]]
NULL
[[5]]
NULL
[[6]]
NULL
[[7]]
NULL
[[8]]
NULL
[[9]]
NULL
[[10]]
NULL
[[11]]
NULL
[[12]]
NULL
[[13]]
NULL
[[14]]
NULL
[[15]]
NULL
[[16]]
NULL
[[17]]
NULL
[[18]]
NULL
[[19]]
NULL
[[20]]
NULL
[[21]]
NULL
[[22]]
NULL
null device 
          1
[CFML_phyml_output.em.txt](https://github.com/xavierdidelot/ClonalFrameML/files/491946/CFML_phyml_output.em.txt)
[CFML_phyml_output.emsim.txt](https://github.com/xavierdidelot/ClonalFrameML/files/491947/CFML_phyml_output.emsim.txt)
[CFML_phyml_output.importation_status.txt](https://github.com/xavierdidelot/ClonalFrameML/files/491945/CFML_phyml_output.importation_status.txt)
[CFML_phyml_output.position_cross_reference.txt](https://github.com/xavierdidelot/ClonalFrameML/files/491948/CFML_phyml_output.position_cross_reference.txt)
[core_sites.txt](https://github.com/xavierdidelot/ClonalFrameML/files/491949/core_sites.txt)
[CFML_phyml_output.labelled_tree.newick.txt](https://github.com/xavierdidelot/ClonalFrameML/files/491959/CFML_phyml_output.labelled_tree.newick.txt)
[CFML_phyml_output.ML_sequence.fasta.txt](https://github.com/xavierdidelot/ClonalFrameML/files/491960/CFML_phyml_output.ML_sequence.fasta.txt)

**Comment by xavierdidelot** [comment]
Hi Shane,

I think it worked and you should now have the pdf file in the directory in which you executed the command. You can ignore the warnings. Don't hesitate to reopen this issue if the pdf is not there.

Best wishes,
Xavier

**Comment by slhogle** [comment]
Hi Xavier,

Thanks for your help! It works fine now that I tried it on my local computer... For some reason when I ran it on our cluster it was not producing the pdf output.

best,
shane

**Comment by StephanieRodrigues** [comment]
Hi guys, 
Do you know if it is possible reorder the tree? I opened  the newick tree that ClonalFrame gave me on FigTree and organized and rooted it like I would like to have in my paper. I saved in newick format with the appropriate name to run the R. script but this message appeared:

Error in if (all(phy$node.label == "")) phy$node.label <- NULL : 
  missing value where TRUE/FALSE needed
Calls: read.tree -> lapply -> FUN
Execution halted

Best 
Stephanie

**Comment by danny-wilson** [comment]
You need to re-root the tree before the ClonalFrameML analysis.

best wishes,
Danny

**Comment by StephanieRodrigues** [comment]
Hey Danny,
Thank you so much, I had this insight before I go to bed yesterday!
I`ll do this!
best,
Stephanie
