### ISSUE TITLE
Version mismatch between source and binary

### ISSUE THREAD

**Issue by tseemann** [xavierdidelot/ClonalFrameML#46]
@xavierdidelot I am still confused by your answer in https://github.com/xavierdidelot/ClonalFrameML/issues/45

The latest binary you or Daniel provide for Linux here
https://github.com/xavierdidelot/ClonalFrameML#download
is 1.25

```
./ClonalFrameML.Ubuntu.12.04.2.LTS  | head -n 1
ClonalFrameML version 1.25
```

Does this mean we are using an OLD version?

**Comment by xavierdidelot** [comment]
Hi Torsten,
Yes, the provided binary version 1.25 is a bit out of date and it would be better to use a more current version by compiling from the latest github source code. The changes are relatively minor though and were made mostly to improve flexibility in the input file formats.
