### ISSUE TITLE
Newick tree issue

### ISSUE THREAD

**Issue by nickswim9** [xavierdidelot/ClonalFrameML#47]
Hi Xavier,

I'm trying to use ClonalFrameML, but I keep getting errors.

First, I performed the multiple alignment using parsnp.

Then I tried to use my parsnp files to run ClonalFrameML. Here is my code:
_./ClonalFrameML /home/nick/Desktop/server/parsnp.tree /home/nick/Desktop/server/parsnp.xmfa output -xmfa_file true_

And this was my output:
_ClonalFrameML v1.0-19-g9488a80
xmfa_file = true
Finished reading in control file._

_Read 17 sequences of length 1460560 sites from /home/nick/Desktop/server/parsnp.xmfa
ERROR: convert_NewickTree_to_marginal_tree(): Newick tree tip label 'GCF_000270445.1_ASM27044v1_genomic.fna' was not expected_

Since parsnp didn't seem to work with ClonalFrameML, I tried using mauve instead.
When trying to use the mauve files as input, I entered this code:
_./ClonalFrameML /home/nick/Desktop/server/"mauve output"/ml.guide_tree /home/nick/Desktop/server/"mauve output"/ml.alignment output -xmfa_file true_

And this was my output:
_ClonalFrameML v1.0-19-g9488a80
xmfa_file = true
Finished reading in control file._

_Read 19 sequences of length 1721579 sites from /home/nick/Desktop/server/mauve output/ml.alignment
ERROR: Token: (
Found left bracket but no right bracket_

Please let me know if you think you know what the problem might be. 

Thanks,
Nick

**Comment by xavierdidelot** [comment]
I've never used parsnp before but there is no reason why it should not work with CFML. You will however need to make sure that the headers of xmfa file correspond exactly to the tip labels in the Newick file, which is presumably what is causing the error. For example in the output you can see that one of the tip labels is "GCF_000270445.1_ASM27044v1_genomic.fna" so you need in your xmfa file header lines looking like this ">GCF_000270445.1_ASM27044v1_genomic.fna". If you can't see to solve it, send me by email your tree and an extract of your xmfa file (say the first block, so up to the first '=' symbol)
