### ISSUE TITLE
ERROR: FASTA_to_nucleotide(): unsupported base

### ISSUE THREAD

**Issue by mhulin** [xavierdidelot/ClonalFrameML#48]
Hi, 

I'm trying to run clonalframeML on a core gene alignment consisting of 902 individual core genes from 102 bacterial strains. I have generated an xmfa file with each alignment separated with a "=" . I am getting this error output: 

ClonalFrameML v1.0-19-g9488a80
xmfa_file = true
ignore_incomplete_sites = true
emsim = 100
Finished reading in control file.

Read 102 sequences of length 1589752 sites from xmfa3
ERROR: FASTA_to_nucleotide(): unsupported base 

I have checked and every genome is included in the 902 alignments. I think the error has something to do with the format of my xmfa file as when I import it into the program geneious it says there is an ambiguous base at the end of the last sequence of each alignment (so next to the "="). I have tried with the sequences wrapped/unwrapped and with/without empty lines between each sequence.  

Many thanks,
Michelle

**Comment by xavierdidelot** [comment]
Hi Michelle,

Could you try with just the first two genes to see if that works (ie truncating your xmfa file after the second '=' symbol). If not, could you send me this file plus your tree so I can see what's wrong?

Best wishes,
Xavier

**Comment by mhulin** [comment]
Hi Xavier, 

It is working for 2 genes!

Best wishes
Michelle

**Comment by xavierdidelot** [comment]
Ok, then keep adding genes until it stops working, and try and see what's wrong with the problematic gene (-:

**Comment by mhulin** [comment]
Hi Xavier, 

I realised the issue was with the xmfa - I had just concatenated fasta files rather than alignments! Thank you for your help, it is working now

Many thanks
Michelle
