### ISSUE TITLE
Question about cfml_results.R script

### ISSUE THREAD

**Issue by MathGon** [xavierdidelot/ClonalFrameML#49]
Salut Xavier,

I manage to perform dataviz of the ClonalFrameML analysis. Unfortunatly, I didn't manage to find the legend of the produced figure and the way to interpret it. 

I also have a problem with the legend when there's too much isolates. I tried to change the line

`axis(1); axis(2,1:nrow(wh.mut),ifelse((1:nrow(wh.mut))<=ceiling(nrow(wh.mut)/2),rownames(wh.mut),"")[od],las=2,cex.axis=.4); box()`

`axis(1); axis(2,1:nrow(wh.mut),ifelse((1:nrow(wh.mut))<=ceiling(nrow(wh.mut)/2),rownames(wh.mut),"")[od],las=2,cex.axis=.2); box()`

It's better but not perfect ([example figure](http://www.mathgon.com/stockage/analysis_clonal.cfml.pdf)). Any idea to solve this misqtke?

Best regards

**Comment by xavierdidelot** [comment]
Salut MathGon,

The dark blue regions represent recombination. Sites that are non polymorphic for a given branch are shown in light blue. Polymorphic sites are shown in a color indicating their level of homoplasy: white is no homoplasy and the range from yellow to red is increasing degrees of homoplasy. You may want to remove this by editing the R script cf line 308.

With that many leaves on the tree labels it's probably impossible to have readable labels, so you might want to remove the axis altogether.

Best wishes,
Xavier
