### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by tseemann** [xavierdidelot/ClonalFrameML#50]
To update the conda/brew packages we need a new release.

Also needed as version on code.google seemed to be "1.7" but here it is "1.0" ?

Could it be 1.8 ?

**Comment by xavierdidelot** [comment]
Done (-:

**Comment by tseemann** [comment]
I don't see any new release at https://github.com/xavierdidelot/ClonalFrameML/releases ?

**Comment by andersgs** [comment]
+1

**Comment by xavierdidelot** [comment]
Hi Torsten,

Sorry about that. I created release version 1.1 in answer to your previous request, but I can see now that this does not solve the problem. Would it work for you if I renamed that release 1.1 to 1.10 ?

Best wishes,
Xavier

**Comment by tseemann** [comment]
@xavierdidelot Yes - anything above your old 1.7 would solve the problem.  Although 1.10 is ambiguous to some parsers (ie. those who treat it as a floating point number as opposed to dotted integers) I think Conda and Brew will be ok.

So if you can make a RELEASE with 1.10 that would help a lot. Thank you!

**Comment by xavierdidelot** [comment]
Done, hope it works!
