### ISSUE TITLE
Error message!

### ISSUE THREAD

**Issue by clementsui** [xavierdidelot/ClonalFrameML#51]
Hello,

I am trying to use clonalframeML but I encountered an error. 
"Read 47 sequences of length 14399 sites from Giardia_allB.fasta
ERROR: convert_NewickTree_to_marginal_tree(): Number of descendant nodes (4) incompatible with a strictly bifurcating rooted tree"

What does it mean? Any advice. I appreciate this. Thanks,

**Comment by xavierdidelot** [comment]
ClonalFrameML does not allow multichotomies in the input tree (except for the root which is allowed to have three descendants since the tree is seen as unrooted). You could resolve this for example using the "multi2di" command of the R package ape.
