### ISSUE TITLE
a_post and b_post

### ISSUE THREAD

**Issue by liuxiong714** [xavierdidelot/ClonalFrameML#52]
Dear Xavier/Daniel,

I have got results like these:
Parameter	Posterior Mean	Posterior Variance	a_post	b_post
R/theta	0.957746	0.0558031	16.4378	17.163
1/delta	0.00720444	3.23E-06	16.085	2232.65
nu	0.737493	0.000592833	917.452	1244.02
s204	0.000181416	1.66E-08	1.9874	10955
s210	0.000270652	2.47E-08	2.96495	10954.8

what's the meaning of a_post and b_post

**Comment by xavierdidelot** [comment]
a_post and b_post are the shape and rate parameters of the posterior Gamma distribution for each parameter. This is useful if you want to know the full distribution, but for most users the mean and variance given in the second and third columns are all that is needed.
