### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by krishnansandeep1980** [xavierdidelot/ClonalFrameML#54]
Dear xavierdidelot,
  I have download ClonalFrameML from github, and installed it with the simple command './make.sh'. I tried it with a tree file and fasta file

./ClonalFrameML example_tree example_fasta output

and got the error message. The tree file looks fine as FigTree can read it. Do you have the idea what causes the problem?

All the best,
krishnansandeep1980

Link to the file I tried on ClonalFrame:
[https://mega.nz/#F!F6YThBCL!Oo8M4GS3sH1WzM-v-FtpjA]

Error message: 
ClonalFrameML v1.10
Finished reading in control file.

Read 10 sequences of length 90358 sites from example_fasta
IMPUTATION AND RECONSTRUCTION OF ANCESTRAL STATES:
Analysing 1880 sites
Empirical nucleotide frequencies:   A 23.5%   C 25%   G 27.7%   T 23.8%
Maximum log-likelihood for imputation and ancestral state reconstruction = -47805.8
Wrote imputed and reconstructed ancestral states to out.ML_sequence.fasta
Wrote position cross-reference file to out.position_cross_reference.txt
BRANCH LENGTH CORRECTION/RECOMBINATION ANALYSIS:
Analysing 90358 sites
Empirical nucleotide frequencies:   A 23.5%   C 25%   G 27.7%   T 23.8%
Beginning branch optimization. Key to parameters (and constraints):
B   uncorrected branch length
L   maximum unnormalized log-posterior per branch
P   contribution of the prior to L
R   R/theta per branch                                       (> 0)
I   mean DNA import length per branch                        (> 0)
D   divergence of DNA imported by recombination              (> 0)
M   expected number of mutations per branch                  (> 0)
Segmentation fault (core dumped)

**Comment by xavierdidelot** [comment]
Thanks for the bug report. I think I have found where the problem was coming from and updated the code accordingly. Please update to the latest github version or release version 1.11. Don't hesitate to reopen this issue if the problem is not fixed.
