### ISSUE TITLE
Output a recombination filtered FASTA

### ISSUE THREAD

**Issue by andersgs** [xavierdidelot/ClonalFrameML#59]
It would be useful for downstream analyses if ClonalFrameML outputted a `recombination filtered` alignment. The current output are not very useful beyond ClonalFrame.

**Comment by kwongj** [comment]
In the interim, you can try: https://github.com/kwongj/maskrc-svg

**Comment by tseemann** [comment]
@xavierdidelot will this feature ever be added? would be very useful to our pipelines.

**Comment by xavierdidelot** [comment]
I have just added this feature in the new version 1.12. It is not used by default but can be activated using -output_filtered true. I hope this helps, I have not tested it a lot, so please let me know if there is anything wrong.

**Comment by raufs** [comment]
Hi Xavier, 

Sorry to re-open this ticket but should the recombination filtered output be equivalent to filtering the input FASTA alignment by all sites listed in the importation_status.txt output file?

Kind regards,
Rauf Salamzade
