### ISSUE TITLE
Did the alignment file must be the core alignment?

### ISSUE THREAD

**Issue by yeswzc** [xavierdidelot/ClonalFrameML#60]
Hi,
Did ClonalFrameML runs on only the core genome?
If so, it cannot detect the recombination which only exist in some of the branch, right?

**Comment by xavierdidelot** [comment]
Yes, ClonalFrameML works mostly on core alignments, although if you have regions that are non-core you can include them using gaps in the alignment for genomes that do not contain that region. This is what happens for example if you use a reference-based mapping technique to produce the alignment.
