### ISSUE TITLE
Is it suitable to use with a core-gene phylogeny?

### ISSUE THREAD

**Issue by iferres** [xavierdidelot/ClonalFrameML#62]
Hi, I was wondering if the software is suitable to use with, for example, roary's output which is a concatenation of core genes aligned, with no intergenic regions. 
Thanks,
Ignacio

**Comment by xavierdidelot** [comment]
Hi Ignacio,

A concatenation of code genes is not ideal as input for ClonalFrameML,
because it messes up with the linkage of the genes. It would be better to
use an alignment against a reference genome, even if there are some regions
that are not core.

Best wishes,
Xavier
