### ISSUE TITLE
ClonalFrameML instead of ClonalFrame

### ISSUE THREAD

**Issue by nbawe** [xavierdidelot/ClonalFrameML#64]
Is it possible to use ClonalFrameML with 7 genes MLST scheme instead of original ClonalFrame?

**Comment by xavierdidelot** [comment]
Yes it is possible, thanks to the option "-xmfa_file true" 
However, for most MLST datasets it probably still makes sense to use the old ClonalFrame version in order to account for uncertainty in the clonal genealogy topology.

**Comment by nbawe** [comment]
Thanks! I have problem with old ClonalFrame as it hangs (progress bar stops) randomly in the middle of the runs. Will still try both. 
1) As for xmfa can it be the same concatenated format as in ClonalFrame? 
2) When using extended MLST about 100 genes can I still use ClonalFrameML with concatenated xmfa?

Thanks

**Comment by xavierdidelot** [comment]
Yes to both.

**Comment by nbawe** [comment]
Thank you Xavier!

**Comment by nbawe** [comment]
@xavierdidelot One more question do you have any idea why i have different number of sites:
1) when using concatenated fasta e.g. core_genomes.fas I get the following:
`Read 7 sequences of length 1487811 sites from core_genomes.fas`
2) when using xmfa e.g. clonalframe.dat. I get the following:
`Read 7 sequences of length 3180811 sites from clonalframe.dat`

**Comment by xavierdidelot** [comment]
That's because when working with a xmfa file, ClonalFrameML inserts 1000bp blank regions between each consecutive block.
