### ISSUE TITLE
importation_status implies recombinations on a sequence longer than input sequences

### ISSUE THREAD

**Issue by signaunc** [xavierdidelot/ClonalFrameML#66]
My MSA is approx. 1 million bps in length (per sample, of course), yet the importation_status file implies recombinations on a sequence which is longer than 2 million bps. 

How can that be?

**Comment by xavierdidelot** [comment]
When working with xmfa, the positions indicated in the
importation_status.txt file need to be interpreted as follows. The
positions are numbered as if the xmfa fragments were concatenated,
with 1000bp regions inserted between each consecutive block. So if
there is a gene of length A and then a gene of length B, the positions
1 to A correspond to the positions in the first gene, and the
positions A+L+1 to A+L+B correspond to the second gene.

**Comment by signaunc** [comment]
Thank you
