### ISSUE TITLE
Error type using core gene alignments

### ISSUE THREAD

**Issue by karchern** [xavierdidelot/ClonalFrameML#67]
Hello, 

there are drawbacks when applying CFML on a core gene alignment (as stated in issue #62). There, you state that a core gene alignment is not ideal as it messes with the linkage of genes which of course cannot be inferred from a core gene alignment.

Could you comment on the kinds of errors that are more likely to happen when one uses a core gene alignment? I.e., are false negatives or false positives more likely?

Since I want to remove the effect of recombinations in order to infer (clonal) phylogeny, I need to control for false negatives as opposed to false positives.

Thank you.

**Comment by xavierdidelot** [comment]
Sorry for the late reply, for some reason I had not seen your question before. The recommended input for CFML is indeed a reference-based alignment, which can be generated either by mapping the raw reads to a reference, or by aligning de novo assemblies against a reference for example using mummer. As mentioned in issue #62 with gene-by-gene alignments linkage between genes is not part of the input which can generate both false positives (FP) and false negatives (FN), especially for shorter genes. It can generate FP for example if the gene context is highly identical and therefore suggests no recombination. It can generate FN for example if two genes are side-by-side and each one on its own is not quite different enough to suggest recombination, but taken together the recombination becomes clear. But more pragmatically, I should also point out that CFML has been tested much more extensively when using reference-based aligned genomes than when using gene-by-gene alignments.

**Comment by nbawe** [comment]
Regarding the issue #69 - So mugsy aligned (not based on the reference alignment isn’t suitable?

**Comment by xavierdidelot** [comment]
It should be fine as long as the alignment is not too broken down into small fragments.

**Comment by nbawe** [comment]
Thanks!

**Comment by thkuo** [comment]
Sorry for continuing with a closed discussion. I do agree that the mapping method is helpful, because it is less time-consuming and allows the users to include indel information. I was just wondering whether it's suggested to remove the reads that cannot be mapped to the reference. In other words, was the example alignment as long as the reference genome?

**Comment by xavierdidelot** [comment]
It's fine if some (or even all) of the genomes do not map in a given region of the reference genome. You can use 'N' or '-' characters to represent this, and this will be treated accordingly by ClonalFrameML. This way you indeed have an alignment that is of the same length as the reference genome.

**Comment by thkuo** [comment]
Many thanks for the reply. The Ns, like you mentioned, can help, but I was wondering whether the sizes and locations can still cause problems. For example, if a dataset includes three samples and their mapping outcomes are:
```
AAAAACCCCCAAAAA sample 1
AAAAANNNNNAAAAA reference 
```
, 
```
AACCTAAAAAAAA sample 2
AANNNAAAAAAAA reference 
```
, and 
```
AATAAAAAAAA sample 3
AANAAAAAAAA reference 
```
Then it seems still hard to create one alignment of the three samples without comparisons among them (ie. the MSA of whole genomes). Was the insertion also a problem during your testing (S. aureus dataset)?

**Comment by xavierdidelot** [comment]
It would be best to use as reference a closed reference without any missing site, so that the problem you mentioned does not arise.

**Comment by thkuo** [comment]
Thank you again
