### ISSUE TITLE
ClonalFrameML is now available on bioconda

### ISSUE THREAD

**Issue by thanhleviet** [xavierdidelot/ClonalFrameML#68]
I made a recipe for ClonalFrameML so that people can easily use [bioconda](http://bioconda.github.io/index.html) system to install the software

`conda install clonalframeml`

**Comment by xavierdidelot** [comment]
Hi Thanh,

This sounds great, but it does not seem to work for me on a new install of miniconda, I'm getting:

PackagesNotFoundError: The following packages are not available from current channels:
  - clonalframeml

Any idea what's going wrong?
Best wishes,
Xavier

**Comment by thanhleviet** [comment]
Hi Xavier,

Did you add bioconda channel into miniconda?
It's quite simple, after you have miniconda installed, just simply run the following command (as instructed at http://bioconda.github.io/) :


`(conda config --add channels r)
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda`

then you can install it ...

http://bioconda.github.io/recipes/clonalframeml/README.html

Sorry for a bit misleading message.

Thanh

**Comment by xavierdidelot** [comment]
Yes, now it's working, thanks for the explanation!
