### ISSUE TITLE
CFML and sample size

### ISSUE THREAD

**Issue by nbawe** [xavierdidelot/ClonalFrameML#69]
What is minimum sample size of CFML? Is 8 genomes aligned with Mauve sufficient?

Thanks

**Comment by xavierdidelot** [comment]
There is no minimum sample size in principle, but of course with just a few genomes it might not be possible to correctly infer the recombination parameters. I think you should try it and see what happens!

**Comment by nbawe** [comment]
Thanks for the answer - have you used mugsy aligned and maf converted in galaxy to fasta with CFML is it suitable for CFML?

**Comment by xavierdidelot** [comment]
No I have never used this and I don't know what how it works, but in principle it should be fine.
