### ISSUE TITLE
Error: convert_NewickTree_to_marginal_tree():

### ISSUE THREAD

**Issue by BioinformaticaUSFQ** [xavierdidelot/ClonalFrameML#70]
Dear Xavier, 

I tried to run ClonalFrameML, with this command: /ClonalFrameML merged.aligned.guide_tree core_alignment example.out -xmfa_file true
ClonalFrameML v1.11-3-g4f13f23
xmfa_file = true
Finished reading in control file.

Read 6 sequences of length 13452023 sites from core_alignment
But I have this ERROR: convert_NewickTree_to_marginal_tree(): Newick tree tip label seq6 was not expected
I read in the issue #17  that maybe can be that the file that I have bootstrap values in your newick file that need to be removed
So  I tried:  perl -i.bk -wpe's/)[0-9]*/g' merged.aligned.guide_tree,
 but I get the following error : Substitution replacement not terminated at -e line 1.

Please can you advice me, Its my first time usign ClonalFrameML

Best Wishes,

Belen

**Comment by xavierdidelot** [comment]
Your problem is that the alignment file and tree file do not label the sequences in the same way.
In your alignment file the sequences are labeled 1, 2, 3, 4, 5 and 6.
In the tree file they are labeled seq1, seq2, seq3, seq4, seq5 and seq6.
If you remove the "seq" from your tree file then it should work (assuming the order is correct)

**Comment by BioinformaticaUSFQ** [comment]
Hi Xavier, 
I am still having problems 
./ClonalFrameML tree3 Alignment_Lep example.out -xmfa_file true -show_progress true
ClonalFrameML v1.11-3-g4f13f23
xmfa_file = true
show_progress = true
Finished reading in control file.

Read 6 sequences of length 13390958 sites from Alignment_Lep
Segmentation fault (core dumped)

Maybe the order in not the correct, what do you think I can try? I have to do other Guide_tree? using another program? 

thanks for your help!
Belen

**Comment by xavierdidelot** [comment]
The recommended method for building the alignment is to use reference mapping, for example BWA, SMALT, Bowtie or Stampy. Or if you only have your genomes as de novo assembled contigs, you could use MUMMER to align them all one by one against a reference genome.

**Comment by jianshu93** [comment]
hello Both, 
I use the software Parsnp to generate xmfa file (https://harvest.readthedocs.io/en/latest/content/parsnp.html), head of XMFA file looks like this:


#SequenceCount 99
##SequenceIndex 1
##SequenceFile Sruber_CM02_Draft.fasta.ref
##SequenceHeader >CM02_NODE_1_length_95569_cov_19.228463
##SequenceLength 3809035bp
##SequenceIndex 2
##SequenceFile Sruber_CZ34_Draft.fasta
##SequenceHeader >CZ34_NODE_1_length_79758_cov_13.749997
##SequenceLength 3878738bp
##SequenceIndex 3
##SequenceFile Sruber_SZ10_Draft.fasta
##SequenceHeader >SZ10_NODE_1_length_87283_cov_9.977626
##SequenceLength 3896705bp
...
...
...

>1:351-1864 + cluster1 s1:p351
cttttcccgctcgggcaccgcgggGGACCTTTTCGTGGGGGCGCCACGGCACGACAC------AAAAAAGCCCCACGGCG
CCGGC-GGCCCCGCAGGGACAGAGAGGTGtgaacggttgcccagggtggattcgaaccaccaGcctcccggtccagagcc
ggacgctctgccgattgagctactgggcaGGCGATTTGCTACActgaatttaaggcaatacacagaatgagtcctctaGc
ggcccggttccgacgcgccgggtgggctGgagggtttgacggacgcttcaccagaggccccgccGGCGGATTGGGCAGGG
...
>2:2803482-2804995 - cluster1 s112:p12058
cttttcccgctcgggcaccgcgggGGACCTTTTCGTGGGGGCGCCACGGCACGATAC------AAAAAAGCCCCACGGCG
CCGGC-GGCCCCGCAGGGACAAAGAGGTGtgaacggttgcccagggtggattcgaaccaccaGcctcccggtccagagcc
ggacgctctgccgattgagctactgggcaAGCGATCTGCTACGctgaatttaaggcaatacacagaatgagtcctctaGc
ggcccggttccgacgcgccgggtgggctGgagggtttgacggacgcttcaccagaggccccgccAGCGGATTGGGCAGGG
GCAc
..
>3:1276738-1278251 + cluster1 s30:p17535
cttttcccgctcgggcaccgcgggGGACCTTTCCGTGGGGGTGCCACGGCACGACAC------AAAAAAGCCCCACGGCG
CCGGC-GGCCCCGCAGGGACAGAGAGGTGtgaacggttgcccagggtggattcgaaccaccaGcctcccggtccagagcc
ggacgctctgccgattgagctactgggcaAGCGATTTGCTACActgaatttaaggcaatacacagaatgagtcctctaGc
ggcccggttccgacgcgccgggtgggctGgagggtttgacggacgcttcaccagaggccccgccGGCGGATTGGGCAGGG
GCCcccgggccctcgtcgatccaccggGCAGCGGCGGCTTCCGTCCCGCTGCGTCCATCGACCGTGTCGAGATCGGCgtc
gcgccagtccgcaatctgctgcgcgattcgggcccgCACGTGTCGCTGCAGGGCCCGGGCCTGGTCCGGCGaacacccgt


I have the same error:  ERROR: convert_NewickTree_to_marginal_tree(): Newick tree tip label 'Sruber_DM09_Draft.fasta' was not expected

I should rename the tree using 1,2,3... to be consistent right. It is so inconvenient that genome alignment did not produce a standard format.

Thanks,

Jianshu

**Comment by xavierdidelot** [comment]
Hi Jianshu,

I don't use parsnp, but you are right that the Newick file needs to have names exactly as in the sequence file, so in your case 1, 2, 3 etc. You could do this by hand if there are not too many, or else edit the Newick file using for example the ape package in R.

Best wishes,
Xavier

**Comment by jianshu93** [comment]
Hello Xavier, 

Thanks for confirm and I have successfully ran ClonalFrameML for about 60 genomes, which are larger than 97% average nucleotide identity to each other. Based on the results (-embranch, see attached figure). How should I interpret it since I saw many homoplasy and recombination events, and they differ quite a lot for those genome that are similar. For those positions I see both homoplasy and recombination, what do they mean. I also attached the R/theta, 1/delta and nu results.

Thanks,

Jianshu


[Alicante_CFML_branch_out.em.txt](https://github.com/xavierdidelot/ClonalFrameML/files/13270745/Alicante_CFML_branch_out.em.txt)

[Alicante_CFML_branch_out.cfml.pdf](https://github.com/xavierdidelot/ClonalFrameML/files/13270739/Alicante_CFML_branch_out.cfml.pdf)

**Comment by xavierdidelot** [comment]
Well done for having got it working. Unless you have a good reason for using embranch, I would suggest using the default setting.
