### ISSUE TITLE
Mismatch between sequence lengths estimated by ClonalFrameML and counted by hand

### ISSUE THREAD

**Issue by ajverster** [xavierdidelot/ClonalFrameML#77]
When I run ClonalFrameML it seems to be adding 1000 bases in between every two sequences in the xmfa. For example, if I have three sequences of total length in /tmp/tmpaqduuvln.xmfa and I run as follows

ClonalFrameML /tmp/tmprfkl376v.txt /tmp/tmpaqduuvln.xmfa /tmp/tmpeze_2ze5 -xmfa_file true

It says

"Read 20 sequences of length 7001 sites from /tmp/tmpaqduuvln.xmfa"

Which looks like it has added two gaps of 1000 bases each. Am I understanding this correctly? Do I need to correct for this when I use the positions in the output of position_cross_reference.txt? I'm asking because I originally noticed there were some recombination events in position_cross_reference.txt that were outside of the total length of the alignment.

Thanks

**Comment by xavierdidelot** [comment]
Yes, you understand correctly. When working with a xmfa file, the positions indicated in the importation_status.txt file need to be interpreted as follows. The positions are numbered as if the xmfa fragments were concatenated, with 1000bp regions inserted between each consecutive block. So if there is a gene of length A and then a gene of length B, the positions 1 to A correspond to the positions in the first gene, and the positions A+L+1 to A+L+B correspond to the second gene.
