### ISSUE TITLE
Something went wrong... or maybe not?

### ISSUE THREAD

**Issue by zseferbekova** [xavierdidelot/ClonalFrameML#79]
Dear Xavier,

I'm trying to infer recombination events in 7 _E. coli_ and 2 _Shigella_ strains using CFML. First, I started by aligning fasta files of whole 9 genomes with **progressiveMauve**:
`progressiveMauve --output=cluster.xmfa *.fna`

Then I extracted core alignment as it is recommended in one of the issues here:
`stripSubsetLCBs cluster.xmfa cluster.xmfa.bbcols core_alignment.xmfa 500`

Then I used a subtree from RAxML tree (constructed for a big set of _E.coli_ genomes) and the core alignment as input files for CFML:
`ClonalFrameML tree.nwk core_alignment.xmfa test -xmfa_file true`

Finally, I used your Rscript and obtained the final [pdf file](https://github.com/xavierdidelot/ClonalFrameML/files/3326887/test.cfml.pdf).

It seems like there are many (I'd say too many) recombination events for some strains. And some genomes are collinear while a reconstructed genome on an internal node has a lot of recombination events. Did I do something wrong or these results are valid?

Thank you for your incredible help with the issues!

**Comment by xavierdidelot** [comment]
If the 9 genomes are sampled from the whole diversity of E. coli (plus Shigella) then we would expect quite a lot of recombination. 

Two of the genomes (3rd and 4th from top to bottom in the figure) are identical or almost identical. Two other genomes (6th and 7th) are very similar, and the last two (8th and 9th) as well except in one region. So we see few events on the branches separating the pairs of closely related genomes, and a lot events on the other branches.

In effect there are only 6 genomes in your dataset, which may not be sufficient for ClonalFrameML to infer correctly all the parameters it is trying to estimate.
