### ISSUE TITLE
Error when set "-initial_values" for R/theta, 1/delta and nu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xavierdidelot/ClonalFrameML#8]
```
Dear Dr. Didelot and Colleagues,

I got the following error when I tried to ru CLFML with per-branch model and 
custom initial_values for for R/theta, 1/delta and nu

ClonalFrameML version 1.25
kappa = 2.36
embranch = true
embranch_dispersion = 0.1
xmfa_file = true
initial_values = 0.101946
ERROR: Syntax error in ArgumentWizard::read_label: option must be prefixed with 
a '-'

Command line:

ClonalFrameML FcC_smatrix_fixed.phy_phyml_tree_rooted.txt 
mbovis_core_aln_header_fixed2.xmfa mbovisRefinedRun_step2 -kappa 2.360 
-embranch true -embranch_dispersion 0.1 -xmfa_file true -initial_values 
"0.101946 0.0465039 0.105836" > mbovisRefinedRun_step2.log.txt

I could be able to figure out where is the command error. 

Best regards
Joaquim



```

Original issue reported on code.google.com by `martins....@gmail.com` on 19 Apr 2015 at 6:29

**Comment by ojonuba** [comment]
Dear Dr. Didelot,
I am also having this problem too. I see you have resolved the issue offline. Can you share the solution with me?

Thanks,

Mustafa (jibrinmo@gmail.com)

**Comment by xavierdidelot** [comment]
Dear Mustafa,

Please check that you used the correct syntax "ClonalFrameML newick_file fasta_file output_file [OPTIONS]" which means options need to be input at the end, after the three mandatory file names. If this does not solve your issue, please post your command line so I can help you further.

Best wishes,
Xavier

**Comment by ojonuba** [comment]
Dear Dr. Didelot,
I found a way around it by copying the command from your wiki on ClonalFrameML and simply edited to suite my needs.

Thanks,
Mustafa

**Comment by xavierdidelot** [comment]
Great!
