### ISSUE TITLE
Core gene alignments from drafts

### ISSUE THREAD

**Issue by matthieu-haudiquet** [xavierdidelot/ClonalFrameML#80]
Hello Xavier, 

I am trying to infer recombination rates of genomes of the same species with CFML.

I am wondering wether I can use ClonalFrameML on several core gene alignments (xfma format) if some of my genomes are draft and so the position of the gene is the one on the contig. Also, should I generate a tree for each gene ? 

Maybe it would be better to just align all the genomes to a complete reference genome and run CFML, but since I have thousands of genomes I'm afraid it would take a very long time. 

What would you recommend ? 

Best, 
Matthieu

**Comment by tseemann** [comment]
Using `parsnp` or `sibelia Z` it would not take very long to align 1000s of draft genomes to a reference.

**Comment by xavierdidelot** [comment]
Yes, or you could use mummer to align each genome one by one against a reference genome.

**Comment by matthieu-haudiquet** [comment]
Thanks a lot for your answers @tseemann and @xavierdidelot . I will try these softwares!

On what criteria would you choose a reference genome in the case of ~4000 genomes from which 200 are complete and the rest are drafts ? (same species, different strains, from NCBI refseq)

**Comment by xavierdidelot** [comment]
I would choose a well known genome, with a good complete genome and good annotation.

**Comment by matthieu-haudiquet** [comment]
Ok, thank you !
