### ISSUE TITLE
please include version.h in release tarball

### ISSUE THREAD

**Issue by EricDeveaud** [xavierdidelot/ClonalFrameML#83]
Hello, 

please include version.h in the release tarball. 
same problem than described on #56 

I was abble to generate a version.h according to the name of the release using this hack

```
bigmess:~src/ClonalFrameML > wget https://github.com/xavierdidelot/ClonalFrameML/archive/v1.11.tar.gz
bigmess:~src/ClonalFrameML > tar xf v1.11.tar.gz 
bigmess:~src/ClonalFrameML > cd ClonalFrameML-1.11/src
bigmess:ClonalFrameML-1.11/src > sed -e "s;\`git describe --tags\`;v$(dirname `pwd` | awk -F- '{print $2}');" makefile > Makefile
bigmess:ClonalFrameML-1.11/src > make -f Makefile
```

regards

Eric

**Comment by xavierdidelot** [comment]
Thanks for reporting this ongoing issue. I will make sure that the version.h is included in future releases.
