### ISSUE TITLE
Packages for 1.12 now built

### ISSUE THREAD

**Issue by tseemann** [xavierdidelot/ClonalFrameML#84]
Brew:
https://github.com/brewsci/homebrew-bio/pull/750/files
DONE!

Conda:
Already done!

See also PR https://github.com/xavierdidelot/ClonalFrameML/pull/85

**Comment by xavierdidelot** [comment]
Brilliant, thank you very much for this Torsten, and also thanks for the pull request to add instructions about how to install using brew and conda.

**Comment by tseemann** [comment]
You're welcome.
