### ISSUE TITLE
How to get the parameter estimates and 95% confidence intervals from result?

### ISSUE THREAD

**Issue by Zjianglin** [xavierdidelot/ClonalFrameML#87]
Dear developers,
    I have run the ClonalFrameML for some genomes and got the `em.txt` and stdout printlog. However, even though the `Mean parameters` in both files are equal, other parametes for each `Branch/Node`  seem different,
eg. 
    stdout log: 
```
Mean parameters:
 L = -6.96866e+06 R = 0.535406 I = 83.9172 D = 0.0320888 M = 0.00262629 in 29393.3 s and 201 evaluations
Parameters per branch:
Branch 19925 B = 0.00795313 R = 0.142417 I = 86.8905 D = 0.0343113 M = 0.00599846
Branch 03915 B = 0.00846593 R = 0.0431743 I = 64.7426 D = 0.0966235 M = 0.00682272
```
    PREFIX_em.txt: 
 ```
Parameter       Branch  Posterior Mean  Posterior Variance      a_post  b_post
R/theta Mean    0.535406        NA      NA      NA
1/delta Mean    0.0119165       NA      NA      NA
nu      Mean    0.0320888       NA      NA      NA
M       Mean    0.00262629      NA      NA      NA
R/theta 19925   0.265999        0.000102293     691.69  2600.35
1/delta 19925   0.965781        0.00134849      691.688 716.195
nu     19925   1.06926 0.000559341     2044.05 1911.64
M       19925   2.284   0.00107318      4860.95 2128.26
R/theta 03915   0.0806385       2.58755e-05     251.302 3116.41
1/delta 03915   1.29617 0.00668555      251.295 193.876
nu      03915   3.01113 0.00596097      1521.04 505.141
M       03915   2.59785 0.00115801      5827.96 2243.38
```

how to interpret this phenomena?

additionally, I saw that we can get the ` the parameter estimates and 95% confidence intervals` from results at your paper, how should I calculate the 95% confidence intervals for each parameters from the result? It seems to should calculate from `em.txt`, but I could only find the mean and std varation for each parameters at different nodes, the features `a_post` and `b_post` confused me a lot.

Could you please help me? Thank you very much.

**Comment by xavierdidelot** [comment]
The values reported for each branch in the ```em.txt``` file are factors that need to be multiplied with the means of the parameters (given in the top four lines) in order to get the per-branch values. So for example for ```nu``` in branch ```19925``` we have ```1.06926*0.0320888=0.03431127``` which is the same as in the ```stdout``` file (denoted ```D``` in that file).

The ```a_post``` and ```b_post``` values are the shape and rate parameters of the posterior distributions. This can be used to get the full distribution, from which you can deduce 95% credible intervals. 

I see you are using ```-embranch true```, please note that you should only do this if you believe the default model (without the ```embranch true``` parameter) is not suitable.

**Comment by xavierdidelot** [comment]
You could use a concatenation of the gene-by-gene alignments, but it is not ideal. I would suggest instead using MUMmer to align each genome against a reference genome. This way the distance between genes along the genomes is preserved, which is important to infer recombination events.

**Comment by Zjianglin** [comment]
Okay, I would try it. Thank you very much.
