### ISSUE TITLE
Input data 

### ISSUE THREAD

**Issue by DarioUH-HI-2019** [xavierdidelot/ClonalFrameML#88]
Dear Dr. Xavier Didelot.

I hope you are well. I am Dario, a Master student of the Univerity of Hawaii at Manoa. I have read your paper about ClonalFrameML. I have found it fascinated and I am sure it will be really helpful for my current research. I want to use ClonalFrameML to infer recombination events across the genomes of different Clavibacter species. All the genomes are complete and fully annotated. 

Since my skills in programming are limited I am using Geneious, which has the plugins of both programs Mauve and PhyML. I am new in programming and my questions are - First, can I use the complete aligning fasta file generated in progressiveMauve or do I have to extract the core alignment first?. Second, to generate the starting tree, do I have to extract first the orthologous genes or I can generate the tree directly with the complete sequences of my nine genomes?

**Comment by xavierdidelot** [comment]
Hi Dario, I don't know Geneious at all, but usually you would need to align your genomes with progressiveMauve, then extract the core from this alignment, then build a phyml tree using this core, and then run ClonalFrameML based on the core alignment plus the phyml tree as starting point. Alternatively, you could extract all genes that are found in all genomes, align them one by one and use this to run both phyml and ClonalFrameML.

**Comment by DarioUH-HI-2019** [comment]
Dear Dr. Xavier Didelot thank so much for your help and support. I really
appreciate that you took your time to reply to my doubts. I hope you have
an excellent day.

Yours sincerely,

Dario Arizala
