### ISSUE TITLE
Size of imports

### ISSUE THREAD

**Issue by noahaus** [xavierdidelot/ClonalFrameML#89]
Greetings!

My question is in regards to interpreting the predicted imports of a WGS alignment. 
I am studying the bacterial pathogen M. bovis, part of the M. tuberculosis complex and was interested to see how different parts of the genome experienced recombination and specifically in differing disease systems worldwide. I mention this to say that I know that the amount of recombination that is present in this dataset is small to none, but I think ClonalFrameML has such a great visualization that I wanted to see this for myself.

What I find is that clonalframeml definitely will find imports, but the size of these imports are around 2 bps long. I did some research myself and believe that recombinant DNA in bacteria should be much larger than this, but as a new comer in studying homologous recombination, I'm not sure what to discard as noise.

The output I got looks like this:
![MI_WGS cfml](https://user-images.githubusercontent.com/40697188/67806495-5ff65500-fa69-11e9-9d10-bdd16c4492bf.png)

 and my importation regions are like this, with short length:
`Node	Beg	End
00-17MIDNRdeerMontm_S23_L001	965327	965345
00-17MIDNRdeerMontm_S23_L001	1535525	1535546
00-17MIDNRdeerMontm_S23_L001	2158241	2158245
00-17MIDNRdeerMontm_S23_L001	3890777	3890779
00-21MIDNRdeerOts_S14_L001	2158136	2158245
00-27MIDNRdeerAlp_S27_L001	1190016	1190024
00-27MIDNRdeerAlp_S27_L001	3845563	3845566
00-32MIDNRdeerOts_S19_L001	332064	332158
00-32MIDNRdeerOts_S19_L001	965343	965345
00-33MIDNRdeerPI_S7_L001	1535525	1535546
00-33MIDNRdeerPI_S7_L001	2158238	2158245
00-43MIDNRdeerMontm_S17_L001	332084	332085
00-43MIDNRdeerMontm_S17_L001	2158241	2158245
00-48MIDNRdeerMontm_S20_L001	332084	332085
00-48MIDNRdeerMontm_S20_L001	965343	965345
00-55MIDNRelk-Montm_S23_L001	332155	332158
00-55MIDNRelk-Montm_S23_L001	965381	965417
00-55MIDNRelk-Montm_S23_L001	1190016	1190020
00-5MIDNRdeerOts_S31_L001	332085	332094
...`

Can I consider the background as noise? Any help with interpretation is greatly appreciated.

**Comment by conmeehan** [comment]
I would say yes that is noise. Likely ClonalFrameML is picking up convergent evolution and not recombination since the fragments are so small. 
Hope that helps.

**Comment by danny-wilson** [comment]
Interesting one. There's more homoplasy in the data than I would have
expected for M. bovis, compared to the number of non-homoplasious sites.

Most blue horizontal lines (excluding the branch with many) appear to
overlap with homoplasies.

It looks like there might be only a few 100 variable positions, which makes
me wonder are the genomes from an outbreak or do they represent
species-wide diversity.

My guess is either the base calling is poor for this dataset, leading to
unrealistically high homoplasy. Or, if the calling is good, perhaps the
homoplasies are occurring mainly at known resistance-determining sites.

Danny

**Comment by xavierdidelot** [comment]
If ClonalFrameML found that the mean length of imports is around 2bp then it is definitely not real recombination but more likely to be mistakes in the alignment.

**Comment by icomas** [comment]
Yes, in our experience the signal is coming either from noise or from regions that accumulate homoplasies . We had a look to recombination in many different ways here (note: Mtb and not Mbo but should be no difference). :

https://advances.sciencemag.org/content/5/6/eaaw3307
There are additional references from other manuscripts looking to the same in the text


Also there is some experimental data showing that Mtbc strains cannot recombine except for the special Mcannetti case:
https://doi.org/10.1073/pnas.1604921113

Hope it helps!
