### ISSUE TITLE
Information on ClonalFrameML output ?

### ISSUE THREAD

**Issue by williamorsi** [xavierdidelot/ClonalFrameML#92]
Dear Xavier,

I am using ClonalFrameML from your 2015 PLOS Comp Biol paper, to try and study the recombination between a set of bacterial genomes.

I am able to feed in the newick tree and core genome fasta alignment and produce the attached output PDF using the R script (output.cfml.pdf).   But, I cant find anywhere on your GitHub page a description of what the different yellow/orange colors mean in the heatmap.  Also what is the difference between the recombination events indicated by the blue squares versus the blue diamonds?  

In the em.txt output what are the a_post and b_post values?  Is the Posterior Mean for the R/theta the 'r/m' value that you describe in the paper?  Do any of these values show the number of recombination events?

Thanks!

Best wishes,

Bill

-- 
Prof. Dr. William D. Orsi
Professor for Geomicrobiology
Department of Earth and Environmental Science, Paleontology & Geobiology
Ludwig-Maximilians-Universität München

**Comment by xavierdidelot** [comment]
Thanks for using ClonalFrameML!

In the graphical output, the dark blue regions represent recombination. Sites that are non polymorphic for a given branch are shown in light blue. Polymorphic sites are shown in a color indicating their level of homoplasy: white is no homoplasy and the range from yellow to red is increasing degrees of homoplasy. You may want to remove this by editing the R script cf line 308.

a_post and b_post are the shape and rate parameters of the posterior Gamma distribution for each parameter. This is useful if you want to know the full distribution, but for most users the mean and variance given in the second and third columns are all that is needed.

R/theta is directly in the output, but to compute r/m you need to use the formula r/m=R/theta*delta*nu
