### ISSUE TITLE
More number of non-core genes in fasta file than tip.labels in newick file?

### ISSUE THREAD

**Issue by Jigyasa3** [xavierdidelot/ClonalFrameML#93]
Dear @xavierdidelot 

I wanted to ask if it's possible to use ClonalFrameML on non-core genes  (i.e the alignment file) where the number of non-core genes is more than the number of tip labels in the .nwk tree.

Thanks!

**Comment by xavierdidelot** [comment]
Yes you can have more genes than you have isolates. But if too many of these genes are missing in too many of the isolates (as suggested by your mention of "non-core" genes) then there could be a lot of uncertainty in the results.

**Comment by Jigyasa3** [comment]
Dear @xavierdidelot 

Thank you for replying!
In response to your suggestion, I have extracted out only those samples for which I have the "non-core" genes.
But I am still running into an error. 
Error-
Read 97 sequences of length 2103 sites from ../../Spirochaete.fasta
ERROR: Number of nodes in Newick tree inconsistent with that expected

I think I am running into this error as my fasta headers have some extract information about the gene names which are absent in the newick file. Is it possible to account for that?

For example, 
gene_name- "Spirochaete1.genename_1"
whereas in newick file, the tip.label is just "Spirochaete1". My notations are consistent, as in the gene names are always after "." in the fasta header. 

Is it possible to read the gene name in the fasta header?

**Comment by xavierdidelot** [comment]
You need to have exactly the same names in the newick file and the fasta file. The error message you get also suggests that your tree does not have the correct number of nodes, which with 97 leaves should be 96 (if the tree is rooted ie two branches come out of the root) or 95 (if the tree is not rooted ie three branches come out of the root)
