### ISSUE TITLE
About ClonalFrameML

### ISSUE THREAD

**Issue by lanlan0210** [xavierdidelot/ClonalFrameML#94]
hi ,I have just learned this software, so I am not very clear about the result. What does the dotted line corresponding to the left phylogenetic tree in the figure obtained using the R script means? And Why do recombination events occur where there is no corresponding strain? Maybe I misunderstood the meaning of the figure. I'm sorry to bother you, I hope you have time to help me, thank you very much!

**Comment by tseemann** [comment]
Was there any info in the Wiki?
https://github.com/xavierdidelot/clonalframeml/wiki
I didn't realise there was a Wiki at first!

**Comment by lanlan0210** [comment]
<img width="548" alt="4cbf5207950698699f931d0438a7f86" src="https://user-images.githubusercontent.com/49662962/76695553-f3988d00-66bb-11ea-8861-6afa79811c77.png">
Thank you for your reply! Take this picture as an example，what does the dotted line mean? And Why is there no corresponding strains  where is a  recombination events ? Did I misunderstand what the picture really meant! Thank you !

**Comment by lanlan0210** [comment]
@tseemann 
<img width="548" alt="4cbf5207950698699f931d0438a7f86" src="https://user-images.githubusercontent.com/49662962/76695741-dc5a9f00-66bd-11ea-818a-b708d96c7db3.png">
Thank you for your reply! Take this picture as an example，what does the dotted line mean? And Why is there no corresponding strains where is a recombination events ? Did I misunderstand what the picture really meant! Thank you !

**Comment by xavierdidelot** [comment]
The dotted lines are there just to help you match the phylogeny on the left and the recombination events on the right. On the right there is a row for each branch of the phylogeny shown on the left. A branch can either be a terminal branch, in which case you can see the name of the genome at the end of that branch, or an internal node, in which case there is no name written. All the events you highlighted in red occurred on internal branches of the phylogeny. For example the lowest red box corresponds to events that occurred on the branch that in ancestral to both genomes TNT and CMUL058.

**Comment by lanlan0210** [comment]
Thank you very much for your reply ! Thanks~~
