### ISSUE TITLE
Kappa calculation from RAxML output

### ISSUE THREAD

**Issue by mmaesaar** [xavierdidelot/ClonalFrameML#95]
Could someone help me calculate kappa value from RAxML output:
```
Tree-Length: 0.028897
rate A <-> C: 2.239533
rate A <-> G: 13.062129
rate A <-> T: 1.119423
rate C <-> G: 1.770590
rate C <-> T: 22.210862
rate G <-> T: 1.000000

freq pi(A): 0.358581
freq pi(C): 0.130893
freq pi(G): 0.185799
freq pi(T): 0.324727
```

Is it calculated as follows:

> kappa = (13.062129+22.210862)/(2.239533+1.119423+1.770590+1.000000) = 35,272991/6,129546 = 5,7545845973

Thanks in advance

**Comment by xavierdidelot** [comment]
I think you need to multiply this by two, because you have two rates in the numerator versus four in the denominator. So we would get:
`2*(13.062129+22.210862)/(2.239533+1.119423+1.770590+1.000000)=11.50917`
Does that make sense?

**Comment by mmaesaar** [comment]
Thanks for the answer. I also asked this from raxml google group if I get an answer I will post it here.

How does it influence the results of CFML when kappa is not defined - does it have significant impact on the recombination detection?

**Comment by xavierdidelot** [comment]
Great, thanks. If kappa is not specified then by default ClonalFrameML uses a value of kappa=2.
In practice the value of kappa will have very little effect on inference.

**Comment by mmaesaar** [comment]
Thanks

**Comment by xavierdidelot** [comment]
[Link](https://groups.google.com/forum/#!topic/raxml/S2B60psdtkw) to Alexis answer in RAxML Google Group
