### ISSUE TITLE
Computation resources usage

### ISSUE THREAD

**Issue by AgustinPardo** [xavierdidelot/ClonalFrameML#97]
Hello,

I would like to know how much computer resoruces the program use and how it change with respect to the input files (length of the sequences, and number of sequences)?

Is there a way to handle the program usage of cpus / cores / threads?

Regards

Agustin

**Comment by xavierdidelot** [comment]
Dear Agustin,

The resources needed to run ClonalFrameML increase more or less linearly with the number of sequences. More than the length of the sequences, what really matters is the number of SNPs in the alignment, which should also have a linear effect on running cost. As an example, running on ~100 sequences of length ~4Mbp with ~10% of sites being SNPs should take less than one day. ClonalFrameML only uses a single core unfortunately at the moment.

Best wishes,
Xavier
