### ISSUE TITLE
Interpreting ClonalFrame output

### ISSUE THREAD

**Issue by StephanieRodrigues** [xavierdidelot/ClonalFrameML#99]
Dear Xavier Didelot, 
Sorry for open a new issue about this theme, I read all issues about how to interpret R/theta, delta and nu values. But I'm still having difficulties (It's the second time that I' using ClonalFrameML).

This is my output:
Parameter | Posterior Mean | Posterior Variance | a_post | b_post
R/theta | 0.0680641 | 7.60E-06 | 609.721 | 8958.03
1/delta | 0.00067429 | 7.64E-10 | 594.87 | 882216
nu | 0.0185318 | 6.54E-08 | 5248.82 | 283233

So, the variance in my R/theta is 0.00000759811, right? How can I calculate the 95% CI? 
How can I transform delta in pb? I read the ClonalFrame paper and to calculate r/m you make R/theta*delta*nu but you used the delta in pb. What would be my delta value in pb in this case? 

Thank you so much,
Best wishes,

Stephanie

**Comment by xavierdidelot** [comment]
Hi Stephanie,

For each parameter, the posterior distribution is Gamma(a_post,b_post) where a_post and b_post are given in the last two columns.
Note that this is using the shape/rate parametrisation of the Gamma distribution.

The mean is equal to a_post/b_post
The variance is equal to a_post/b_post^2
You can get the 95%CI using in R something like:
`qgamma(c(0.025,0.975),shape=a_post,rate=b_post)`

delta is the inverse of 1/delta. So for example if you use the command above to find that the 95%CI of 1/delta is 0.010 to 0.002 then the 95%CI of delta is 500bp to 1000bp.

Best wishes,
Xavier
